//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIQDesktop.CIQProductIdentityServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CProductIdentity", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceWebRole")]
    [System.SerializableAttribute()]
    public partial class CProductIdentity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductCategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductClassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductIdentityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductSubcategoryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductCategory {
            get {
                return this.ProductCategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductCategoryField, value) != true)) {
                    this.ProductCategoryField = value;
                    this.RaisePropertyChanged("ProductCategory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductClass {
            get {
                return this.ProductClassField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductClassField, value) != true)) {
                    this.ProductClassField = value;
                    this.RaisePropertyChanged("ProductClass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductIdentity {
            get {
                return this.ProductIdentityField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductIdentityField, value) != true)) {
                    this.ProductIdentityField = value;
                    this.RaisePropertyChanged("ProductIdentity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductSubcategory {
            get {
                return this.ProductSubcategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductSubcategoryField, value) != true)) {
                    this.ProductSubcategoryField = value;
                    this.RaisePropertyChanged("ProductSubcategory");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CIQProductIdentityServices.ICIQProductIdentityServices")]
    public interface ICIQProductIdentityServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICIQProductIdentityServices/CreateProductIdentityInstance", ReplyAction="http://tempuri.org/ICIQProductIdentityServices/CreateProductIdentityInstanceRespo" +
            "nse")]
        CIQDesktop.CIQProductIdentityServices.CProductIdentity CreateProductIdentityInstance();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICIQProductIdentityServices/SaveProductIdentity", ReplyAction="http://tempuri.org/ICIQProductIdentityServices/SaveProductIdentityResponse")]
        bool SaveProductIdentity(CIQDesktop.CIQProductIdentityServices.CProductIdentity cPI, string flattenedProduct);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICIQProductIdentityServices/QueryKind", ReplyAction="http://tempuri.org/ICIQProductIdentityServices/QueryKindResponse")]
        CIQDesktop.CIQProductIdentityServices.CProductIdentity[] QueryKind(string flattenedProduct);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICIQProductIdentityServices/MapIdentity", ReplyAction="http://tempuri.org/ICIQProductIdentityServices/MapIdentityResponse")]
        bool MapIdentity(string mapping, string productIdentity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICIQProductIdentityServices/QueryIdentity", ReplyAction="http://tempuri.org/ICIQProductIdentityServices/QueryIdentityResponse")]
        CIQDesktop.CIQProductIdentityServices.CProductIdentity QueryIdentity(string productCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICIQProductIdentityServices/QueryProduct", ReplyAction="http://tempuri.org/ICIQProductIdentityServices/QueryProductResponse")]
        string QueryProduct(string productCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICIQProductIdentityServicesChannel : CIQDesktop.CIQProductIdentityServices.ICIQProductIdentityServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CIQProductIdentityServicesClient : System.ServiceModel.ClientBase<CIQDesktop.CIQProductIdentityServices.ICIQProductIdentityServices>, CIQDesktop.CIQProductIdentityServices.ICIQProductIdentityServices {
        
        public CIQProductIdentityServicesClient() {
        }
        
        public CIQProductIdentityServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CIQProductIdentityServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CIQProductIdentityServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CIQProductIdentityServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CIQDesktop.CIQProductIdentityServices.CProductIdentity CreateProductIdentityInstance() {
            return base.Channel.CreateProductIdentityInstance();
        }
        
        public bool SaveProductIdentity(CIQDesktop.CIQProductIdentityServices.CProductIdentity cPI, string flattenedProduct) {
            return base.Channel.SaveProductIdentity(cPI, flattenedProduct);
        }
        
        public CIQDesktop.CIQProductIdentityServices.CProductIdentity[] QueryKind(string flattenedProduct) {
            return base.Channel.QueryKind(flattenedProduct);
        }
        
        public bool MapIdentity(string mapping, string productIdentity) {
            return base.Channel.MapIdentity(mapping, productIdentity);
        }
        
        public CIQDesktop.CIQProductIdentityServices.CProductIdentity QueryIdentity(string productCode) {
            return base.Channel.QueryIdentity(productCode);
        }
        
        public string QueryProduct(string productCode) {
            return base.Channel.QueryProduct(productCode);
        }
    }
}
