//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIQDesktop.CIQAffiliateServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ProductAds", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceWebRole", ItemName="CProductAd")]
    [System.SerializableAttribute()]
    public class ProductAds : System.Collections.Generic.List<CIQDesktop.CIQAffiliateServices.CProductAd> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CProductAd", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceWebRole")]
    [System.SerializableAttribute()]
    public partial class CProductAd : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid AdGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrandImageUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double DiscountAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPercentageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ManufacturerCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MarketerIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid AdGuid {
            get {
                return this.AdGuidField;
            }
            set {
                if ((this.AdGuidField.Equals(value) != true)) {
                    this.AdGuidField = value;
                    this.RaisePropertyChanged("AdGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdText {
            get {
                return this.AdTextField;
            }
            set {
                if ((object.ReferenceEquals(this.AdTextField, value) != true)) {
                    this.AdTextField = value;
                    this.RaisePropertyChanged("AdText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdTitle {
            get {
                return this.AdTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.AdTitleField, value) != true)) {
                    this.AdTitleField = value;
                    this.RaisePropertyChanged("AdTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BrandImageUrl {
            get {
                return this.BrandImageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.BrandImageUrlField, value) != true)) {
                    this.BrandImageUrlField = value;
                    this.RaisePropertyChanged("BrandImageUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double DiscountAmount {
            get {
                return this.DiscountAmountField;
            }
            set {
                if ((this.DiscountAmountField.Equals(value) != true)) {
                    this.DiscountAmountField = value;
                    this.RaisePropertyChanged("DiscountAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageUrl {
            get {
                return this.ImageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageUrlField, value) != true)) {
                    this.ImageUrlField = value;
                    this.RaisePropertyChanged("ImageUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPercentage {
            get {
                return this.IsPercentageField;
            }
            set {
                if ((this.IsPercentageField.Equals(value) != true)) {
                    this.IsPercentageField = value;
                    this.RaisePropertyChanged("IsPercentage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ManufacturerCode {
            get {
                return this.ManufacturerCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ManufacturerCodeField, value) != true)) {
                    this.ManufacturerCodeField = value;
                    this.RaisePropertyChanged("ManufacturerCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MarketerID {
            get {
                return this.MarketerIDField;
            }
            set {
                if ((this.MarketerIDField.Equals(value) != true)) {
                    this.MarketerIDField = value;
                    this.RaisePropertyChanged("MarketerID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ProductProperties", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceWebRole", ItemName="entry", KeyName="property", ValueName="value")]
    [System.SerializableAttribute()]
    public class ProductProperties : System.Collections.Generic.Dictionary<string, string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CIQAffiliateServices.ICIQPlatform")]
    public interface ICIQPlatform {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICIQPlatform/GetAdList", ReplyAction="http://tempuri.org/ICIQPlatform/GetAdListResponse")]
        CIQDesktop.CIQAffiliateServices.ProductAds GetAdList(System.Guid affiliateID, string scannedCode, double lon, double lat, int adsToReturn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICIQPlatform/GetAdDetails", ReplyAction="http://tempuri.org/ICIQPlatform/GetAdDetailsResponse")]
        CIQDesktop.CIQAffiliateServices.CProductAd GetAdDetails(System.Guid affiliateID, string scannedCode, double lon, double lat, System.Guid adGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICIQPlatform/GetAdCoupon", ReplyAction="http://tempuri.org/ICIQPlatform/GetAdCouponResponse")]
        CIQDesktop.CIQAffiliateServices.CProductAd GetAdCoupon(System.Guid affiliateID, string scannedCode, double lon, double lat, System.Guid redeemGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICIQPlatform/GetProductInformation", ReplyAction="http://tempuri.org/ICIQPlatform/GetProductInformationResponse")]
        CIQDesktop.CIQAffiliateServices.ProductProperties GetProductInformation(System.Guid affiliateID, string scannedCode, double lon, double lat);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICIQPlatformChannel : CIQDesktop.CIQAffiliateServices.ICIQPlatform, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CIQPlatformClient : System.ServiceModel.ClientBase<CIQDesktop.CIQAffiliateServices.ICIQPlatform>, CIQDesktop.CIQAffiliateServices.ICIQPlatform {
        
        public CIQPlatformClient() {
        }
        
        public CIQPlatformClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CIQPlatformClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CIQPlatformClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CIQPlatformClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CIQDesktop.CIQAffiliateServices.ProductAds GetAdList(System.Guid affiliateID, string scannedCode, double lon, double lat, int adsToReturn) {
            return base.Channel.GetAdList(affiliateID, scannedCode, lon, lat, adsToReturn);
        }
        
        public CIQDesktop.CIQAffiliateServices.CProductAd GetAdDetails(System.Guid affiliateID, string scannedCode, double lon, double lat, System.Guid adGuid) {
            return base.Channel.GetAdDetails(affiliateID, scannedCode, lon, lat, adGuid);
        }
        
        public CIQDesktop.CIQAffiliateServices.CProductAd GetAdCoupon(System.Guid affiliateID, string scannedCode, double lon, double lat, System.Guid redeemGuid) {
            return base.Channel.GetAdCoupon(affiliateID, scannedCode, lon, lat, redeemGuid);
        }
        
        public CIQDesktop.CIQAffiliateServices.ProductProperties GetProductInformation(System.Guid affiliateID, string scannedCode, double lon, double lat) {
            return base.Channel.GetProductInformation(affiliateID, scannedCode, lon, lat);
        }
    }
}
