//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIQDesktop.CIQAdServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CAd", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceWebRole")]
    [System.SerializableAttribute()]
    public partial class CAd : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrandImageUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float DiscountAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiscountCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDiscountAPercentageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MarketerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdText {
            get {
                return this.AdTextField;
            }
            set {
                if ((object.ReferenceEquals(this.AdTextField, value) != true)) {
                    this.AdTextField = value;
                    this.RaisePropertyChanged("AdText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BrandImageUrl {
            get {
                return this.BrandImageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.BrandImageUrlField, value) != true)) {
                    this.BrandImageUrlField = value;
                    this.RaisePropertyChanged("BrandImageUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float DiscountAmount {
            get {
                return this.DiscountAmountField;
            }
            set {
                if ((this.DiscountAmountField.Equals(value) != true)) {
                    this.DiscountAmountField = value;
                    this.RaisePropertyChanged("DiscountAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiscountCode {
            get {
                return this.DiscountCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.DiscountCodeField, value) != true)) {
                    this.DiscountCodeField = value;
                    this.RaisePropertyChanged("DiscountCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageUrl {
            get {
                return this.ImageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageUrlField, value) != true)) {
                    this.ImageUrlField = value;
                    this.RaisePropertyChanged("ImageUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDiscountAPercentage {
            get {
                return this.IsDiscountAPercentageField;
            }
            set {
                if ((this.IsDiscountAPercentageField.Equals(value) != true)) {
                    this.IsDiscountAPercentageField = value;
                    this.RaisePropertyChanged("IsDiscountAPercentage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MarketerID {
            get {
                return this.MarketerIDField;
            }
            set {
                if ((this.MarketerIDField.Equals(value) != true)) {
                    this.MarketerIDField = value;
                    this.RaisePropertyChanged("MarketerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CIQAdServices.ICIQAdServices")]
    public interface ICIQAdServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICIQAdServices/CreateAdInstance", ReplyAction="http://tempuri.org/ICIQAdServices/CreateAdInstanceResponse")]
        CIQDesktop.CIQAdServices.CAd CreateAdInstance();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICIQAdServices/GetAds", ReplyAction="http://tempuri.org/ICIQAdServices/GetAdsResponse")]
        CIQDesktop.CIQAdServices.CAd[] GetAds(int MarketerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICIQAdServices/GetAd", ReplyAction="http://tempuri.org/ICIQAdServices/GetAdResponse")]
        CIQDesktop.CIQAdServices.CAd GetAd(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICIQAdServices/SaveAd", ReplyAction="http://tempuri.org/ICIQAdServices/SaveAdResponse")]
        bool SaveAd(CIQDesktop.CIQAdServices.CAd anAd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICIQAdServices/DeleteAd", ReplyAction="http://tempuri.org/ICIQAdServices/DeleteAdResponse")]
        bool DeleteAd(int ID, bool deleteAssociatedBids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICIQAdServices/UpdateAd", ReplyAction="http://tempuri.org/ICIQAdServices/UpdateAdResponse")]
        bool UpdateAd(CIQDesktop.CIQAdServices.CAd anAd);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICIQAdServicesChannel : CIQDesktop.CIQAdServices.ICIQAdServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CIQAdServicesClient : System.ServiceModel.ClientBase<CIQDesktop.CIQAdServices.ICIQAdServices>, CIQDesktop.CIQAdServices.ICIQAdServices {
        
        public CIQAdServicesClient() {
        }
        
        public CIQAdServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CIQAdServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CIQAdServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CIQAdServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CIQDesktop.CIQAdServices.CAd CreateAdInstance() {
            return base.Channel.CreateAdInstance();
        }
        
        public CIQDesktop.CIQAdServices.CAd[] GetAds(int MarketerID) {
            return base.Channel.GetAds(MarketerID);
        }
        
        public CIQDesktop.CIQAdServices.CAd GetAd(int ID) {
            return base.Channel.GetAd(ID);
        }
        
        public bool SaveAd(CIQDesktop.CIQAdServices.CAd anAd) {
            return base.Channel.SaveAd(anAd);
        }
        
        public bool DeleteAd(int ID, bool deleteAssociatedBids) {
            return base.Channel.DeleteAd(ID, deleteAssociatedBids);
        }
        
        public bool UpdateAd(CIQDesktop.CIQAdServices.CAd anAd) {
            return base.Channel.UpdateAd(anAd);
        }
    }
}
