//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIQDesktop.CIQBidServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CBid", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceWebRole")]
    [System.SerializableAttribute()]
    public partial class CBid : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AssociatedAdIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DayOfWeekField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MarketerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductCategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductClassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductSubcategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SerializedProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimeOfDayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AssociatedAdID {
            get {
                return this.AssociatedAdIDField;
            }
            set {
                if ((this.AssociatedAdIDField.Equals(value) != true)) {
                    this.AssociatedAdIDField = value;
                    this.RaisePropertyChanged("AssociatedAdID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DayOfWeek {
            get {
                return this.DayOfWeekField;
            }
            set {
                if ((object.ReferenceEquals(this.DayOfWeekField, value) != true)) {
                    this.DayOfWeekField = value;
                    this.RaisePropertyChanged("DayOfWeek");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MarketerID {
            get {
                return this.MarketerIDField;
            }
            set {
                if ((this.MarketerIDField.Equals(value) != true)) {
                    this.MarketerIDField = value;
                    this.RaisePropertyChanged("MarketerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductCategory {
            get {
                return this.ProductCategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductCategoryField, value) != true)) {
                    this.ProductCategoryField = value;
                    this.RaisePropertyChanged("ProductCategory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductClass {
            get {
                return this.ProductClassField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductClassField, value) != true)) {
                    this.ProductClassField = value;
                    this.RaisePropertyChanged("ProductClass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductSubcategory {
            get {
                return this.ProductSubcategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductSubcategoryField, value) != true)) {
                    this.ProductSubcategoryField = value;
                    this.RaisePropertyChanged("ProductSubcategory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Region {
            get {
                return this.RegionField;
            }
            set {
                if ((object.ReferenceEquals(this.RegionField, value) != true)) {
                    this.RegionField = value;
                    this.RaisePropertyChanged("Region");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SerializedProduct {
            get {
                return this.SerializedProductField;
            }
            set {
                if ((object.ReferenceEquals(this.SerializedProductField, value) != true)) {
                    this.SerializedProductField = value;
                    this.RaisePropertyChanged("SerializedProduct");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TimeOfDay {
            get {
                return this.TimeOfDayField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeOfDayField, value) != true)) {
                    this.TimeOfDayField = value;
                    this.RaisePropertyChanged("TimeOfDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CIQBidServices.ICIQBidServices")]
    public interface ICIQBidServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICIQBidServices/CreateBidInstance", ReplyAction="http://tempuri.org/ICIQBidServices/CreateBidInstanceResponse")]
        CIQDesktop.CIQBidServices.CBid CreateBidInstance();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICIQBidServices/GetBids", ReplyAction="http://tempuri.org/ICIQBidServices/GetBidsResponse")]
        CIQDesktop.CIQBidServices.CBid[] GetBids(int MarketerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICIQBidServices/SaveBid", ReplyAction="http://tempuri.org/ICIQBidServices/SaveBidResponse")]
        bool SaveBid(CIQDesktop.CIQBidServices.CBid aBid, string flattenedProduct);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICIQBidServices/DeleteBid", ReplyAction="http://tempuri.org/ICIQBidServices/DeleteBidResponse")]
        bool DeleteBid(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICIQBidServices/UpdateBid", ReplyAction="http://tempuri.org/ICIQBidServices/UpdateBidResponse")]
        bool UpdateBid(CIQDesktop.CIQBidServices.CBid aBid, string flattenedProduct);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICIQBidServices/ComputeScanHistory", ReplyAction="http://tempuri.org/ICIQBidServices/ComputeScanHistoryResponse")]
        double ComputeScanHistory(CIQDesktop.CIQBidServices.CBid aBid, string bidProd, double howManyDaysBack);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICIQBidServices/AssociatedToAd", ReplyAction="http://tempuri.org/ICIQBidServices/AssociatedToAdResponse")]
        CIQDesktop.CIQBidServices.CBid[] AssociatedToAd(int adID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICIQBidServicesChannel : CIQDesktop.CIQBidServices.ICIQBidServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CIQBidServicesClient : System.ServiceModel.ClientBase<CIQDesktop.CIQBidServices.ICIQBidServices>, CIQDesktop.CIQBidServices.ICIQBidServices {
        
        public CIQBidServicesClient() {
        }
        
        public CIQBidServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CIQBidServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CIQBidServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CIQBidServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CIQDesktop.CIQBidServices.CBid CreateBidInstance() {
            return base.Channel.CreateBidInstance();
        }
        
        public CIQDesktop.CIQBidServices.CBid[] GetBids(int MarketerID) {
            return base.Channel.GetBids(MarketerID);
        }
        
        public bool SaveBid(CIQDesktop.CIQBidServices.CBid aBid, string flattenedProduct) {
            return base.Channel.SaveBid(aBid, flattenedProduct);
        }
        
        public bool DeleteBid(int ID) {
            return base.Channel.DeleteBid(ID);
        }
        
        public bool UpdateBid(CIQDesktop.CIQBidServices.CBid aBid, string flattenedProduct) {
            return base.Channel.UpdateBid(aBid, flattenedProduct);
        }
        
        public double ComputeScanHistory(CIQDesktop.CIQBidServices.CBid aBid, string bidProd, double howManyDaysBack) {
            return base.Channel.ComputeScanHistory(aBid, bidProd, howManyDaysBack);
        }
        
        public CIQDesktop.CIQBidServices.CBid[] AssociatedToAd(int adID) {
            return base.Channel.AssociatedToAd(adID);
        }
    }
}
