//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace WP7AdFinder.CIQProductServices {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CProduct", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceWebRole")]
    public partial class CProduct : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ProductClassificationField;
        
        private System.Collections.Generic.List<WP7AdFinder.CIQProductServices.CProperty> ProductPropertiesField;
        
        private int VersionIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductClassification {
            get {
                return this.ProductClassificationField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductClassificationField, value) != true)) {
                    this.ProductClassificationField = value;
                    this.RaisePropertyChanged("ProductClassification");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<WP7AdFinder.CIQProductServices.CProperty> ProductProperties {
            get {
                return this.ProductPropertiesField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductPropertiesField, value) != true)) {
                    this.ProductPropertiesField = value;
                    this.RaisePropertyChanged("ProductProperties");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VersionID {
            get {
                return this.VersionIDField;
            }
            set {
                if ((this.VersionIDField.Equals(value) != true)) {
                    this.VersionIDField = value;
                    this.RaisePropertyChanged("VersionID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CProperty", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceWebRole")]
    public partial class CProperty : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string PropertyNameField;
        
        private string PropertyValueField;
        
        private System.Collections.Generic.List<string> ValidValuesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PropertyName {
            get {
                return this.PropertyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertyNameField, value) != true)) {
                    this.PropertyNameField = value;
                    this.RaisePropertyChanged("PropertyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PropertyValue {
            get {
                return this.PropertyValueField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertyValueField, value) != true)) {
                    this.PropertyValueField = value;
                    this.RaisePropertyChanged("PropertyValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> ValidValues {
            get {
                return this.ValidValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.ValidValuesField, value) != true)) {
                    this.ValidValuesField = value;
                    this.RaisePropertyChanged("ValidValues");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CIQProductServices.ICIQProductServices")]
    public interface ICIQProductServices {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ICIQProductServices/CreateProductInstance", ReplyAction="http://tempuri.org/ICIQProductServices/CreateProductInstanceResponse")]
        System.IAsyncResult BeginCreateProductInstance(string productClassification, bool isForBidUsage, System.AsyncCallback callback, object asyncState);
        
        WP7AdFinder.CIQProductServices.CProduct EndCreateProductInstance(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ICIQProductServices/Serialize", ReplyAction="http://tempuri.org/ICIQProductServices/SerializeResponse")]
        System.IAsyncResult BeginSerialize(WP7AdFinder.CIQProductServices.CProduct aProduct, ref string outString, System.AsyncCallback callback, object asyncState);
        
        bool EndSerialize(ref string outString, System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ICIQProductServices/Deserialize", ReplyAction="http://tempuri.org/ICIQProductServices/DeserializeResponse")]
        System.IAsyncResult BeginDeserialize(string inString, System.AsyncCallback callback, object asyncState);
        
        WP7AdFinder.CIQProductServices.CProduct EndDeserialize(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ICIQProductServices/GetProductCategories", ReplyAction="http://tempuri.org/ICIQProductServices/GetProductCategoriesResponse")]
        System.IAsyncResult BeginGetProductCategories(bool isForBidUsage, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<string> EndGetProductCategories(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ICIQProductServices/GetProductSubcategories", ReplyAction="http://tempuri.org/ICIQProductServices/GetProductSubcategoriesResponse")]
        System.IAsyncResult BeginGetProductSubcategories(string sCategory, bool isForBidUsage, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<string> EndGetProductSubcategories(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ICIQProductServices/GetProductClassifications", ReplyAction="http://tempuri.org/ICIQProductServices/GetProductClassificationsResponse")]
        System.IAsyncResult BeginGetProductClassifications(string sCategory, string sSubcategory, bool isForBidUsage, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<string> EndGetProductClassifications(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICIQProductServicesChannel : WP7AdFinder.CIQProductServices.ICIQProductServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreateProductInstanceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CreateProductInstanceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WP7AdFinder.CIQProductServices.CProduct Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WP7AdFinder.CIQProductServices.CProduct)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SerializeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SerializeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string outString {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeserializeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public DeserializeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WP7AdFinder.CIQProductServices.CProduct Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WP7AdFinder.CIQProductServices.CProduct)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetProductCategoriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetProductCategoriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<string> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<string>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetProductSubcategoriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetProductSubcategoriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<string> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<string>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetProductClassificationsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetProductClassificationsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<string> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<string>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CIQProductServicesClient : System.ServiceModel.ClientBase<WP7AdFinder.CIQProductServices.ICIQProductServices>, WP7AdFinder.CIQProductServices.ICIQProductServices {
        
        private BeginOperationDelegate onBeginCreateProductInstanceDelegate;
        
        private EndOperationDelegate onEndCreateProductInstanceDelegate;
        
        private System.Threading.SendOrPostCallback onCreateProductInstanceCompletedDelegate;
        
        private BeginOperationDelegate onBeginSerializeDelegate;
        
        private EndOperationDelegate onEndSerializeDelegate;
        
        private System.Threading.SendOrPostCallback onSerializeCompletedDelegate;
        
        private BeginOperationDelegate onBeginDeserializeDelegate;
        
        private EndOperationDelegate onEndDeserializeDelegate;
        
        private System.Threading.SendOrPostCallback onDeserializeCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetProductCategoriesDelegate;
        
        private EndOperationDelegate onEndGetProductCategoriesDelegate;
        
        private System.Threading.SendOrPostCallback onGetProductCategoriesCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetProductSubcategoriesDelegate;
        
        private EndOperationDelegate onEndGetProductSubcategoriesDelegate;
        
        private System.Threading.SendOrPostCallback onGetProductSubcategoriesCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetProductClassificationsDelegate;
        
        private EndOperationDelegate onEndGetProductClassificationsDelegate;
        
        private System.Threading.SendOrPostCallback onGetProductClassificationsCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public CIQProductServicesClient() {
        }
        
        public CIQProductServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CIQProductServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CIQProductServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CIQProductServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<CreateProductInstanceCompletedEventArgs> CreateProductInstanceCompleted;
        
        public event System.EventHandler<SerializeCompletedEventArgs> SerializeCompleted;
        
        public event System.EventHandler<DeserializeCompletedEventArgs> DeserializeCompleted;
        
        public event System.EventHandler<GetProductCategoriesCompletedEventArgs> GetProductCategoriesCompleted;
        
        public event System.EventHandler<GetProductSubcategoriesCompletedEventArgs> GetProductSubcategoriesCompleted;
        
        public event System.EventHandler<GetProductClassificationsCompletedEventArgs> GetProductClassificationsCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WP7AdFinder.CIQProductServices.ICIQProductServices.BeginCreateProductInstance(string productClassification, bool isForBidUsage, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCreateProductInstance(productClassification, isForBidUsage, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WP7AdFinder.CIQProductServices.CProduct WP7AdFinder.CIQProductServices.ICIQProductServices.EndCreateProductInstance(System.IAsyncResult result) {
            return base.Channel.EndCreateProductInstance(result);
        }
        
        private System.IAsyncResult OnBeginCreateProductInstance(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string productClassification = ((string)(inValues[0]));
            bool isForBidUsage = ((bool)(inValues[1]));
            return ((WP7AdFinder.CIQProductServices.ICIQProductServices)(this)).BeginCreateProductInstance(productClassification, isForBidUsage, callback, asyncState);
        }
        
        private object[] OnEndCreateProductInstance(System.IAsyncResult result) {
            WP7AdFinder.CIQProductServices.CProduct retVal = ((WP7AdFinder.CIQProductServices.ICIQProductServices)(this)).EndCreateProductInstance(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCreateProductInstanceCompleted(object state) {
            if ((this.CreateProductInstanceCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CreateProductInstanceCompleted(this, new CreateProductInstanceCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CreateProductInstanceAsync(string productClassification, bool isForBidUsage) {
            this.CreateProductInstanceAsync(productClassification, isForBidUsage, null);
        }
        
        public void CreateProductInstanceAsync(string productClassification, bool isForBidUsage, object userState) {
            if ((this.onBeginCreateProductInstanceDelegate == null)) {
                this.onBeginCreateProductInstanceDelegate = new BeginOperationDelegate(this.OnBeginCreateProductInstance);
            }
            if ((this.onEndCreateProductInstanceDelegate == null)) {
                this.onEndCreateProductInstanceDelegate = new EndOperationDelegate(this.OnEndCreateProductInstance);
            }
            if ((this.onCreateProductInstanceCompletedDelegate == null)) {
                this.onCreateProductInstanceCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCreateProductInstanceCompleted);
            }
            base.InvokeAsync(this.onBeginCreateProductInstanceDelegate, new object[] {
                        productClassification,
                        isForBidUsage}, this.onEndCreateProductInstanceDelegate, this.onCreateProductInstanceCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WP7AdFinder.CIQProductServices.ICIQProductServices.BeginSerialize(WP7AdFinder.CIQProductServices.CProduct aProduct, ref string outString, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSerialize(aProduct, ref outString, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool WP7AdFinder.CIQProductServices.ICIQProductServices.EndSerialize(ref string outString, System.IAsyncResult result) {
            return base.Channel.EndSerialize(ref outString, result);
        }
        
        private System.IAsyncResult OnBeginSerialize(object[] inValues, System.AsyncCallback callback, object asyncState) {
            WP7AdFinder.CIQProductServices.CProduct aProduct = ((WP7AdFinder.CIQProductServices.CProduct)(inValues[0]));
            string outString = ((string)(inValues[1]));
            return ((WP7AdFinder.CIQProductServices.ICIQProductServices)(this)).BeginSerialize(aProduct, ref outString, callback, asyncState);
        }
        
        private object[] OnEndSerialize(System.IAsyncResult result) {
            string outString = this.GetDefaultValueForInitialization<string>();
            bool retVal = ((WP7AdFinder.CIQProductServices.ICIQProductServices)(this)).EndSerialize(ref outString, result);
            return new object[] {
                    outString,
                    retVal};
        }
        
        private void OnSerializeCompleted(object state) {
            if ((this.SerializeCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SerializeCompleted(this, new SerializeCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SerializeAsync(WP7AdFinder.CIQProductServices.CProduct aProduct, string outString) {
            this.SerializeAsync(aProduct, outString, null);
        }
        
        public void SerializeAsync(WP7AdFinder.CIQProductServices.CProduct aProduct, string outString, object userState) {
            if ((this.onBeginSerializeDelegate == null)) {
                this.onBeginSerializeDelegate = new BeginOperationDelegate(this.OnBeginSerialize);
            }
            if ((this.onEndSerializeDelegate == null)) {
                this.onEndSerializeDelegate = new EndOperationDelegate(this.OnEndSerialize);
            }
            if ((this.onSerializeCompletedDelegate == null)) {
                this.onSerializeCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSerializeCompleted);
            }
            base.InvokeAsync(this.onBeginSerializeDelegate, new object[] {
                        aProduct,
                        outString}, this.onEndSerializeDelegate, this.onSerializeCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WP7AdFinder.CIQProductServices.ICIQProductServices.BeginDeserialize(string inString, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDeserialize(inString, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WP7AdFinder.CIQProductServices.CProduct WP7AdFinder.CIQProductServices.ICIQProductServices.EndDeserialize(System.IAsyncResult result) {
            return base.Channel.EndDeserialize(result);
        }
        
        private System.IAsyncResult OnBeginDeserialize(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string inString = ((string)(inValues[0]));
            return ((WP7AdFinder.CIQProductServices.ICIQProductServices)(this)).BeginDeserialize(inString, callback, asyncState);
        }
        
        private object[] OnEndDeserialize(System.IAsyncResult result) {
            WP7AdFinder.CIQProductServices.CProduct retVal = ((WP7AdFinder.CIQProductServices.ICIQProductServices)(this)).EndDeserialize(result);
            return new object[] {
                    retVal};
        }
        
        private void OnDeserializeCompleted(object state) {
            if ((this.DeserializeCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeserializeCompleted(this, new DeserializeCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DeserializeAsync(string inString) {
            this.DeserializeAsync(inString, null);
        }
        
        public void DeserializeAsync(string inString, object userState) {
            if ((this.onBeginDeserializeDelegate == null)) {
                this.onBeginDeserializeDelegate = new BeginOperationDelegate(this.OnBeginDeserialize);
            }
            if ((this.onEndDeserializeDelegate == null)) {
                this.onEndDeserializeDelegate = new EndOperationDelegate(this.OnEndDeserialize);
            }
            if ((this.onDeserializeCompletedDelegate == null)) {
                this.onDeserializeCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeserializeCompleted);
            }
            base.InvokeAsync(this.onBeginDeserializeDelegate, new object[] {
                        inString}, this.onEndDeserializeDelegate, this.onDeserializeCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WP7AdFinder.CIQProductServices.ICIQProductServices.BeginGetProductCategories(bool isForBidUsage, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetProductCategories(isForBidUsage, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<string> WP7AdFinder.CIQProductServices.ICIQProductServices.EndGetProductCategories(System.IAsyncResult result) {
            return base.Channel.EndGetProductCategories(result);
        }
        
        private System.IAsyncResult OnBeginGetProductCategories(object[] inValues, System.AsyncCallback callback, object asyncState) {
            bool isForBidUsage = ((bool)(inValues[0]));
            return ((WP7AdFinder.CIQProductServices.ICIQProductServices)(this)).BeginGetProductCategories(isForBidUsage, callback, asyncState);
        }
        
        private object[] OnEndGetProductCategories(System.IAsyncResult result) {
            System.Collections.Generic.List<string> retVal = ((WP7AdFinder.CIQProductServices.ICIQProductServices)(this)).EndGetProductCategories(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetProductCategoriesCompleted(object state) {
            if ((this.GetProductCategoriesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetProductCategoriesCompleted(this, new GetProductCategoriesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetProductCategoriesAsync(bool isForBidUsage) {
            this.GetProductCategoriesAsync(isForBidUsage, null);
        }
        
        public void GetProductCategoriesAsync(bool isForBidUsage, object userState) {
            if ((this.onBeginGetProductCategoriesDelegate == null)) {
                this.onBeginGetProductCategoriesDelegate = new BeginOperationDelegate(this.OnBeginGetProductCategories);
            }
            if ((this.onEndGetProductCategoriesDelegate == null)) {
                this.onEndGetProductCategoriesDelegate = new EndOperationDelegate(this.OnEndGetProductCategories);
            }
            if ((this.onGetProductCategoriesCompletedDelegate == null)) {
                this.onGetProductCategoriesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetProductCategoriesCompleted);
            }
            base.InvokeAsync(this.onBeginGetProductCategoriesDelegate, new object[] {
                        isForBidUsage}, this.onEndGetProductCategoriesDelegate, this.onGetProductCategoriesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WP7AdFinder.CIQProductServices.ICIQProductServices.BeginGetProductSubcategories(string sCategory, bool isForBidUsage, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetProductSubcategories(sCategory, isForBidUsage, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<string> WP7AdFinder.CIQProductServices.ICIQProductServices.EndGetProductSubcategories(System.IAsyncResult result) {
            return base.Channel.EndGetProductSubcategories(result);
        }
        
        private System.IAsyncResult OnBeginGetProductSubcategories(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string sCategory = ((string)(inValues[0]));
            bool isForBidUsage = ((bool)(inValues[1]));
            return ((WP7AdFinder.CIQProductServices.ICIQProductServices)(this)).BeginGetProductSubcategories(sCategory, isForBidUsage, callback, asyncState);
        }
        
        private object[] OnEndGetProductSubcategories(System.IAsyncResult result) {
            System.Collections.Generic.List<string> retVal = ((WP7AdFinder.CIQProductServices.ICIQProductServices)(this)).EndGetProductSubcategories(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetProductSubcategoriesCompleted(object state) {
            if ((this.GetProductSubcategoriesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetProductSubcategoriesCompleted(this, new GetProductSubcategoriesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetProductSubcategoriesAsync(string sCategory, bool isForBidUsage) {
            this.GetProductSubcategoriesAsync(sCategory, isForBidUsage, null);
        }
        
        public void GetProductSubcategoriesAsync(string sCategory, bool isForBidUsage, object userState) {
            if ((this.onBeginGetProductSubcategoriesDelegate == null)) {
                this.onBeginGetProductSubcategoriesDelegate = new BeginOperationDelegate(this.OnBeginGetProductSubcategories);
            }
            if ((this.onEndGetProductSubcategoriesDelegate == null)) {
                this.onEndGetProductSubcategoriesDelegate = new EndOperationDelegate(this.OnEndGetProductSubcategories);
            }
            if ((this.onGetProductSubcategoriesCompletedDelegate == null)) {
                this.onGetProductSubcategoriesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetProductSubcategoriesCompleted);
            }
            base.InvokeAsync(this.onBeginGetProductSubcategoriesDelegate, new object[] {
                        sCategory,
                        isForBidUsage}, this.onEndGetProductSubcategoriesDelegate, this.onGetProductSubcategoriesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WP7AdFinder.CIQProductServices.ICIQProductServices.BeginGetProductClassifications(string sCategory, string sSubcategory, bool isForBidUsage, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetProductClassifications(sCategory, sSubcategory, isForBidUsage, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<string> WP7AdFinder.CIQProductServices.ICIQProductServices.EndGetProductClassifications(System.IAsyncResult result) {
            return base.Channel.EndGetProductClassifications(result);
        }
        
        private System.IAsyncResult OnBeginGetProductClassifications(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string sCategory = ((string)(inValues[0]));
            string sSubcategory = ((string)(inValues[1]));
            bool isForBidUsage = ((bool)(inValues[2]));
            return ((WP7AdFinder.CIQProductServices.ICIQProductServices)(this)).BeginGetProductClassifications(sCategory, sSubcategory, isForBidUsage, callback, asyncState);
        }
        
        private object[] OnEndGetProductClassifications(System.IAsyncResult result) {
            System.Collections.Generic.List<string> retVal = ((WP7AdFinder.CIQProductServices.ICIQProductServices)(this)).EndGetProductClassifications(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetProductClassificationsCompleted(object state) {
            if ((this.GetProductClassificationsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetProductClassificationsCompleted(this, new GetProductClassificationsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetProductClassificationsAsync(string sCategory, string sSubcategory, bool isForBidUsage) {
            this.GetProductClassificationsAsync(sCategory, sSubcategory, isForBidUsage, null);
        }
        
        public void GetProductClassificationsAsync(string sCategory, string sSubcategory, bool isForBidUsage, object userState) {
            if ((this.onBeginGetProductClassificationsDelegate == null)) {
                this.onBeginGetProductClassificationsDelegate = new BeginOperationDelegate(this.OnBeginGetProductClassifications);
            }
            if ((this.onEndGetProductClassificationsDelegate == null)) {
                this.onEndGetProductClassificationsDelegate = new EndOperationDelegate(this.OnEndGetProductClassifications);
            }
            if ((this.onGetProductClassificationsCompletedDelegate == null)) {
                this.onGetProductClassificationsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetProductClassificationsCompleted);
            }
            base.InvokeAsync(this.onBeginGetProductClassificationsDelegate, new object[] {
                        sCategory,
                        sSubcategory,
                        isForBidUsage}, this.onEndGetProductClassificationsDelegate, this.onGetProductClassificationsCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override WP7AdFinder.CIQProductServices.ICIQProductServices CreateChannel() {
            return new CIQProductServicesClientChannel(this);
        }
        
        private class CIQProductServicesClientChannel : ChannelBase<WP7AdFinder.CIQProductServices.ICIQProductServices>, WP7AdFinder.CIQProductServices.ICIQProductServices {
            
            public CIQProductServicesClientChannel(System.ServiceModel.ClientBase<WP7AdFinder.CIQProductServices.ICIQProductServices> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginCreateProductInstance(string productClassification, bool isForBidUsage, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = productClassification;
                _args[1] = isForBidUsage;
                System.IAsyncResult _result = base.BeginInvoke("CreateProductInstance", _args, callback, asyncState);
                return _result;
            }
            
            public WP7AdFinder.CIQProductServices.CProduct EndCreateProductInstance(System.IAsyncResult result) {
                object[] _args = new object[0];
                WP7AdFinder.CIQProductServices.CProduct _result = ((WP7AdFinder.CIQProductServices.CProduct)(base.EndInvoke("CreateProductInstance", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSerialize(WP7AdFinder.CIQProductServices.CProduct aProduct, ref string outString, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = aProduct;
                _args[1] = outString;
                System.IAsyncResult _result = base.BeginInvoke("Serialize", _args, callback, asyncState);
                outString = ((string)(_args[1]));
                return _result;
            }
            
            public bool EndSerialize(ref string outString, System.IAsyncResult result) {
                object[] _args = new object[1];
                _args[0] = outString;
                bool _result = ((bool)(base.EndInvoke("Serialize", _args, result)));
                outString = ((string)(_args[0]));
                return _result;
            }
            
            public System.IAsyncResult BeginDeserialize(string inString, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = inString;
                System.IAsyncResult _result = base.BeginInvoke("Deserialize", _args, callback, asyncState);
                return _result;
            }
            
            public WP7AdFinder.CIQProductServices.CProduct EndDeserialize(System.IAsyncResult result) {
                object[] _args = new object[0];
                WP7AdFinder.CIQProductServices.CProduct _result = ((WP7AdFinder.CIQProductServices.CProduct)(base.EndInvoke("Deserialize", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetProductCategories(bool isForBidUsage, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = isForBidUsage;
                System.IAsyncResult _result = base.BeginInvoke("GetProductCategories", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<string> EndGetProductCategories(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<string> _result = ((System.Collections.Generic.List<string>)(base.EndInvoke("GetProductCategories", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetProductSubcategories(string sCategory, bool isForBidUsage, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = sCategory;
                _args[1] = isForBidUsage;
                System.IAsyncResult _result = base.BeginInvoke("GetProductSubcategories", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<string> EndGetProductSubcategories(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<string> _result = ((System.Collections.Generic.List<string>)(base.EndInvoke("GetProductSubcategories", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetProductClassifications(string sCategory, string sSubcategory, bool isForBidUsage, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = sCategory;
                _args[1] = sSubcategory;
                _args[2] = isForBidUsage;
                System.IAsyncResult _result = base.BeginInvoke("GetProductClassifications", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<string> EndGetProductClassifications(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<string> _result = ((System.Collections.Generic.List<string>)(base.EndInvoke("GetProductClassifications", _args, result)));
                return _result;
            }
        }
    }
}
