//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIQDesktop.CIQProductServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CProduct", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceWebRole")]
    [System.SerializableAttribute()]
    public partial class CProduct : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductClassificationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CIQDesktop.CIQProductServices.CProperty[] ProductPropertiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VersionIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductClassification {
            get {
                return this.ProductClassificationField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductClassificationField, value) != true)) {
                    this.ProductClassificationField = value;
                    this.RaisePropertyChanged("ProductClassification");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CIQDesktop.CIQProductServices.CProperty[] ProductProperties {
            get {
                return this.ProductPropertiesField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductPropertiesField, value) != true)) {
                    this.ProductPropertiesField = value;
                    this.RaisePropertyChanged("ProductProperties");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VersionID {
            get {
                return this.VersionIDField;
            }
            set {
                if ((this.VersionIDField.Equals(value) != true)) {
                    this.VersionIDField = value;
                    this.RaisePropertyChanged("VersionID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CProperty", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceWebRole")]
    [System.SerializableAttribute()]
    public partial class CProperty : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PropertyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PropertyValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ValidValuesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PropertyName {
            get {
                return this.PropertyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertyNameField, value) != true)) {
                    this.PropertyNameField = value;
                    this.RaisePropertyChanged("PropertyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PropertyValue {
            get {
                return this.PropertyValueField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertyValueField, value) != true)) {
                    this.PropertyValueField = value;
                    this.RaisePropertyChanged("PropertyValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ValidValues {
            get {
                return this.ValidValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.ValidValuesField, value) != true)) {
                    this.ValidValuesField = value;
                    this.RaisePropertyChanged("ValidValues");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CIQProductServices.ICIQProductServices")]
    public interface ICIQProductServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICIQProductServices/CreateProductInstance", ReplyAction="http://tempuri.org/ICIQProductServices/CreateProductInstanceResponse")]
        CIQDesktop.CIQProductServices.CProduct CreateProductInstance(string productClassification, bool isForBidUsage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICIQProductServices/Serialize", ReplyAction="http://tempuri.org/ICIQProductServices/SerializeResponse")]
        bool Serialize(CIQDesktop.CIQProductServices.CProduct aProduct, ref string outString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICIQProductServices/Deserialize", ReplyAction="http://tempuri.org/ICIQProductServices/DeserializeResponse")]
        CIQDesktop.CIQProductServices.CProduct Deserialize(string inString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICIQProductServices/GetProductCategories", ReplyAction="http://tempuri.org/ICIQProductServices/GetProductCategoriesResponse")]
        string[] GetProductCategories(bool isForBidUsage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICIQProductServices/GetProductSubcategories", ReplyAction="http://tempuri.org/ICIQProductServices/GetProductSubcategoriesResponse")]
        string[] GetProductSubcategories(string sCategory, bool isForBidUsage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICIQProductServices/GetProductClassifications", ReplyAction="http://tempuri.org/ICIQProductServices/GetProductClassificationsResponse")]
        string[] GetProductClassifications(string sCategory, string sSubcategory, bool isForBidUsage);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICIQProductServicesChannel : CIQDesktop.CIQProductServices.ICIQProductServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CIQProductServicesClient : System.ServiceModel.ClientBase<CIQDesktop.CIQProductServices.ICIQProductServices>, CIQDesktop.CIQProductServices.ICIQProductServices {
        
        public CIQProductServicesClient() {
        }
        
        public CIQProductServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CIQProductServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CIQProductServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CIQProductServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CIQDesktop.CIQProductServices.CProduct CreateProductInstance(string productClassification, bool isForBidUsage) {
            return base.Channel.CreateProductInstance(productClassification, isForBidUsage);
        }
        
        public bool Serialize(CIQDesktop.CIQProductServices.CProduct aProduct, ref string outString) {
            return base.Channel.Serialize(aProduct, ref outString);
        }
        
        public CIQDesktop.CIQProductServices.CProduct Deserialize(string inString) {
            return base.Channel.Deserialize(inString);
        }
        
        public string[] GetProductCategories(bool isForBidUsage) {
            return base.Channel.GetProductCategories(isForBidUsage);
        }
        
        public string[] GetProductSubcategories(string sCategory, bool isForBidUsage) {
            return base.Channel.GetProductSubcategories(sCategory, isForBidUsage);
        }
        
        public string[] GetProductClassifications(string sCategory, string sSubcategory, bool isForBidUsage) {
            return base.Channel.GetProductClassifications(sCategory, sSubcategory, isForBidUsage);
        }
    }
}
