//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("CIQPlatformModel", "FK_Bids_0", "DiscountAd", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(WCFServiceWebRole.DiscountAd), "Bid", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WCFServiceWebRole.Bid), true)]

#endregion

namespace WCFServiceWebRole
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CIQPlatformEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CIQPlatformEntities object using the connection string found in the 'CIQPlatformEntities' section of the application configuration file.
        /// </summary>
        public CIQPlatformEntities() : base("name=CIQPlatformEntities", "CIQPlatformEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CIQPlatformEntities object.
        /// </summary>
        public CIQPlatformEntities(string connectionString) : base(connectionString, "CIQPlatformEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CIQPlatformEntities object.
        /// </summary>
        public CIQPlatformEntities(EntityConnection connection) : base(connection, "CIQPlatformEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ProductClass> ProductClasses
        {
            get
            {
                if ((_ProductClasses == null))
                {
                    _ProductClasses = base.CreateObjectSet<ProductClass>("ProductClasses");
                }
                return _ProductClasses;
            }
        }
        private ObjectSet<ProductClass> _ProductClasses;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ProductCode> ProductCodes
        {
            get
            {
                if ((_ProductCodes == null))
                {
                    _ProductCodes = base.CreateObjectSet<ProductCode>("ProductCodes");
                }
                return _ProductCodes;
            }
        }
        private ObjectSet<ProductCode> _ProductCodes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ProductTaxonomy> ProductTaxonomies
        {
            get
            {
                if ((_ProductTaxonomies == null))
                {
                    _ProductTaxonomies = base.CreateObjectSet<ProductTaxonomy>("ProductTaxonomies");
                }
                return _ProductTaxonomies;
            }
        }
        private ObjectSet<ProductTaxonomy> _ProductTaxonomies;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MappingCode> MappingCodes
        {
            get
            {
                if ((_MappingCodes == null))
                {
                    _MappingCodes = base.CreateObjectSet<MappingCode>("MappingCodes");
                }
                return _MappingCodes;
            }
        }
        private ObjectSet<MappingCode> _MappingCodes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ScanActivity> ScanActivities
        {
            get
            {
                if ((_ScanActivities == null))
                {
                    _ScanActivities = base.CreateObjectSet<ScanActivity>("ScanActivities");
                }
                return _ScanActivities;
            }
        }
        private ObjectSet<ScanActivity> _ScanActivities;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Brand> Brands
        {
            get
            {
                if ((_Brands == null))
                {
                    _Brands = base.CreateObjectSet<Brand>("Brands");
                }
                return _Brands;
            }
        }
        private ObjectSet<Brand> _Brands;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Company> Companies
        {
            get
            {
                if ((_Companies == null))
                {
                    _Companies = base.CreateObjectSet<Company>("Companies");
                }
                return _Companies;
            }
        }
        private ObjectSet<Company> _Companies;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Member> Members
        {
            get
            {
                if ((_Members == null))
                {
                    _Members = base.CreateObjectSet<Member>("Members");
                }
                return _Members;
            }
        }
        private ObjectSet<Member> _Members;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Bid> Bids
        {
            get
            {
                if ((_Bids == null))
                {
                    _Bids = base.CreateObjectSet<Bid>("Bids");
                }
                return _Bids;
            }
        }
        private ObjectSet<Bid> _Bids;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DiscountAd> DiscountAds
        {
            get
            {
                if ((_DiscountAds == null))
                {
                    _DiscountAds = base.CreateObjectSet<DiscountAd>("DiscountAds");
                }
                return _DiscountAds;
            }
        }
        private ObjectSet<DiscountAd> _DiscountAds;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Impression> Impressions
        {
            get
            {
                if ((_Impressions == null))
                {
                    _Impressions = base.CreateObjectSet<Impression>("Impressions");
                }
                return _Impressions;
            }
        }
        private ObjectSet<Impression> _Impressions;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ProductClasses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProductClasses(ProductClass productClass)
        {
            base.AddObject("ProductClasses", productClass);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ProductCodes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProductCodes(ProductCode productCode)
        {
            base.AddObject("ProductCodes", productCode);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ProductTaxonomies EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProductTaxonomies(ProductTaxonomy productTaxonomy)
        {
            base.AddObject("ProductTaxonomies", productTaxonomy);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MappingCodes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMappingCodes(MappingCode mappingCode)
        {
            base.AddObject("MappingCodes", mappingCode);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ScanActivities EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToScanActivities(ScanActivity scanActivity)
        {
            base.AddObject("ScanActivities", scanActivity);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Brands EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBrands(Brand brand)
        {
            base.AddObject("Brands", brand);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Companies EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCompanies(Company company)
        {
            base.AddObject("Companies", company);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Members EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMembers(Member member)
        {
            base.AddObject("Members", member);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Bids EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBids(Bid bid)
        {
            base.AddObject("Bids", bid);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DiscountAds EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDiscountAds(DiscountAd discountAd)
        {
            base.AddObject("DiscountAds", discountAd);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Impressions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToImpressions(Impression impression)
        {
            base.AddObject("Impressions", impression);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CIQPlatformModel", Name="Bid")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Bid : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Bid object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Bid CreateBid(global::System.Int32 id)
        {
            Bid bid = new Bid();
            bid.ID = id;
            return bid;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProdCategory
        {
            get
            {
                return _ProdCategory;
            }
            set
            {
                OnProdCategoryChanging(value);
                ReportPropertyChanging("ProdCategory");
                _ProdCategory = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProdCategory");
                OnProdCategoryChanged();
            }
        }
        private global::System.String _ProdCategory;
        partial void OnProdCategoryChanging(global::System.String value);
        partial void OnProdCategoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProdSubcategory
        {
            get
            {
                return _ProdSubcategory;
            }
            set
            {
                OnProdSubcategoryChanging(value);
                ReportPropertyChanging("ProdSubcategory");
                _ProdSubcategory = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProdSubcategory");
                OnProdSubcategoryChanged();
            }
        }
        private global::System.String _ProdSubcategory;
        partial void OnProdSubcategoryChanging(global::System.String value);
        partial void OnProdSubcategoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProdClass
        {
            get
            {
                return _ProdClass;
            }
            set
            {
                OnProdClassChanging(value);
                ReportPropertyChanging("ProdClass");
                _ProdClass = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProdClass");
                OnProdClassChanged();
            }
        }
        private global::System.String _ProdClass;
        partial void OnProdClassChanging(global::System.String value);
        partial void OnProdClassChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProdBlob
        {
            get
            {
                return _ProdBlob;
            }
            set
            {
                OnProdBlobChanging(value);
                ReportPropertyChanging("ProdBlob");
                _ProdBlob = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProdBlob");
                OnProdBlobChanged();
            }
        }
        private global::System.String _ProdBlob;
        partial void OnProdBlobChanging(global::System.String value);
        partial void OnProdBlobChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> AssociatedAd
        {
            get
            {
                return _AssociatedAd;
            }
            set
            {
                OnAssociatedAdChanging(value);
                ReportPropertyChanging("AssociatedAd");
                _AssociatedAd = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AssociatedAd");
                OnAssociatedAdChanged();
            }
        }
        private Nullable<global::System.Int32> _AssociatedAd;
        partial void OnAssociatedAdChanging(Nullable<global::System.Int32> value);
        partial void OnAssociatedAdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MarketerID
        {
            get
            {
                return _MarketerID;
            }
            set
            {
                OnMarketerIDChanging(value);
                ReportPropertyChanging("MarketerID");
                _MarketerID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MarketerID");
                OnMarketerIDChanged();
            }
        }
        private Nullable<global::System.Int32> _MarketerID;
        partial void OnMarketerIDChanging(Nullable<global::System.Int32> value);
        partial void OnMarketerIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Region
        {
            get
            {
                return _Region;
            }
            set
            {
                OnRegionChanging(value);
                ReportPropertyChanging("Region");
                _Region = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Region");
                OnRegionChanged();
            }
        }
        private global::System.String _Region;
        partial void OnRegionChanging(global::System.String value);
        partial void OnRegionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TimeOfDay
        {
            get
            {
                return _TimeOfDay;
            }
            set
            {
                OnTimeOfDayChanging(value);
                ReportPropertyChanging("TimeOfDay");
                _TimeOfDay = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TimeOfDay");
                OnTimeOfDayChanged();
            }
        }
        private global::System.String _TimeOfDay;
        partial void OnTimeOfDayChanging(global::System.String value);
        partial void OnTimeOfDayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DayOfWeek
        {
            get
            {
                return _DayOfWeek;
            }
            set
            {
                OnDayOfWeekChanging(value);
                ReportPropertyChanging("DayOfWeek");
                _DayOfWeek = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DayOfWeek");
                OnDayOfWeekChanged();
            }
        }
        private global::System.String _DayOfWeek;
        partial void OnDayOfWeekChanging(global::System.String value);
        partial void OnDayOfWeekChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CIQPlatformModel", "FK_Bids_0", "DiscountAd")]
        public DiscountAd DiscountAd
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DiscountAd>("CIQPlatformModel.FK_Bids_0", "DiscountAd").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DiscountAd>("CIQPlatformModel.FK_Bids_0", "DiscountAd").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<DiscountAd> DiscountAdReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DiscountAd>("CIQPlatformModel.FK_Bids_0", "DiscountAd");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<DiscountAd>("CIQPlatformModel.FK_Bids_0", "DiscountAd", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CIQPlatformModel", Name="Brand")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Brand : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Brand object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="brandName">Initial value of the BrandName property.</param>
        /// <param name="cID">Initial value of the cID property.</param>
        public static Brand CreateBrand(global::System.Int32 id, global::System.String brandName, global::System.Int32 cID)
        {
            Brand brand = new Brand();
            brand.ID = id;
            brand.BrandName = brandName;
            brand.cID = cID;
            return brand;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BrandName
        {
            get
            {
                return _BrandName;
            }
            set
            {
                OnBrandNameChanging(value);
                ReportPropertyChanging("BrandName");
                _BrandName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("BrandName");
                OnBrandNameChanged();
            }
        }
        private global::System.String _BrandName;
        partial void OnBrandNameChanging(global::System.String value);
        partial void OnBrandNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 cID
        {
            get
            {
                return _cID;
            }
            set
            {
                OncIDChanging(value);
                ReportPropertyChanging("cID");
                _cID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cID");
                OncIDChanged();
            }
        }
        private global::System.Int32 _cID;
        partial void OncIDChanging(global::System.Int32 value);
        partial void OncIDChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CIQPlatformModel", Name="Company")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Company : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Company object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="website">Initial value of the Website property.</param>
        /// <param name="type">Initial value of the Type property.</param>
        public static Company CreateCompany(global::System.Int32 id, global::System.String name, global::System.String website, global::System.Int32 type)
        {
            Company company = new Company();
            company.ID = id;
            company.Name = name;
            company.Website = website;
            company.Type = type;
            return company;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Website
        {
            get
            {
                return _Website;
            }
            set
            {
                OnWebsiteChanging(value);
                ReportPropertyChanging("Website");
                _Website = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Website");
                OnWebsiteChanged();
            }
        }
        private global::System.String _Website;
        partial void OnWebsiteChanging(global::System.String value);
        partial void OnWebsiteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.Int32 _Type;
        partial void OnTypeChanging(global::System.Int32 value);
        partial void OnTypeChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CIQPlatformModel", Name="DiscountAd")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DiscountAd : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DiscountAd object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="marketerID">Initial value of the MarketerID property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="discountAmount">Initial value of the DiscountAmount property.</param>
        /// <param name="discountIsPercentage">Initial value of the DiscountIsPercentage property.</param>
        /// <param name="discountCode">Initial value of the DiscountCode property.</param>
        public static DiscountAd CreateDiscountAd(global::System.Int32 id, global::System.Int32 marketerID, global::System.String title, global::System.Double discountAmount, global::System.Boolean discountIsPercentage, global::System.String discountCode)
        {
            DiscountAd discountAd = new DiscountAd();
            discountAd.ID = id;
            discountAd.MarketerID = marketerID;
            discountAd.Title = title;
            discountAd.DiscountAmount = discountAmount;
            discountAd.DiscountIsPercentage = discountIsPercentage;
            discountAd.DiscountCode = discountCode;
            return discountAd;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MarketerID
        {
            get
            {
                return _MarketerID;
            }
            set
            {
                OnMarketerIDChanging(value);
                ReportPropertyChanging("MarketerID");
                _MarketerID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MarketerID");
                OnMarketerIDChanged();
            }
        }
        private global::System.Int32 _MarketerID;
        partial void OnMarketerIDChanging(global::System.Int32 value);
        partial void OnMarketerIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AdText
        {
            get
            {
                return _AdText;
            }
            set
            {
                OnAdTextChanging(value);
                ReportPropertyChanging("AdText");
                _AdText = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AdText");
                OnAdTextChanged();
            }
        }
        private global::System.String _AdText;
        partial void OnAdTextChanging(global::System.String value);
        partial void OnAdTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImageUrl
        {
            get
            {
                return _ImageUrl;
            }
            set
            {
                OnImageUrlChanging(value);
                ReportPropertyChanging("ImageUrl");
                _ImageUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ImageUrl");
                OnImageUrlChanged();
            }
        }
        private global::System.String _ImageUrl;
        partial void OnImageUrlChanging(global::System.String value);
        partial void OnImageUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double DiscountAmount
        {
            get
            {
                return _DiscountAmount;
            }
            set
            {
                OnDiscountAmountChanging(value);
                ReportPropertyChanging("DiscountAmount");
                _DiscountAmount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DiscountAmount");
                OnDiscountAmountChanged();
            }
        }
        private global::System.Double _DiscountAmount;
        partial void OnDiscountAmountChanging(global::System.Double value);
        partial void OnDiscountAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean DiscountIsPercentage
        {
            get
            {
                return _DiscountIsPercentage;
            }
            set
            {
                OnDiscountIsPercentageChanging(value);
                ReportPropertyChanging("DiscountIsPercentage");
                _DiscountIsPercentage = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DiscountIsPercentage");
                OnDiscountIsPercentageChanged();
            }
        }
        private global::System.Boolean _DiscountIsPercentage;
        partial void OnDiscountIsPercentageChanging(global::System.Boolean value);
        partial void OnDiscountIsPercentageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DiscountCode
        {
            get
            {
                return _DiscountCode;
            }
            set
            {
                OnDiscountCodeChanging(value);
                ReportPropertyChanging("DiscountCode");
                _DiscountCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DiscountCode");
                OnDiscountCodeChanged();
            }
        }
        private global::System.String _DiscountCode;
        partial void OnDiscountCodeChanging(global::System.String value);
        partial void OnDiscountCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BrandImageUrl
        {
            get
            {
                return _BrandImageUrl;
            }
            set
            {
                OnBrandImageUrlChanging(value);
                ReportPropertyChanging("BrandImageUrl");
                _BrandImageUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BrandImageUrl");
                OnBrandImageUrlChanged();
            }
        }
        private global::System.String _BrandImageUrl;
        partial void OnBrandImageUrlChanging(global::System.String value);
        partial void OnBrandImageUrlChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CIQPlatformModel", "FK_Bids_0", "Bid")]
        public EntityCollection<Bid> Bids
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Bid>("CIQPlatformModel.FK_Bids_0", "Bid");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Bid>("CIQPlatformModel.FK_Bids_0", "Bid", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CIQPlatformModel", Name="Impression")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Impression : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Impression object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="compositeID">Initial value of the CompositeID property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        /// <param name="companyID">Initial value of the CompanyID property.</param>
        /// <param name="marketerID">Initial value of the MarketerID property.</param>
        /// <param name="bidID">Initial value of the BidID property.</param>
        /// <param name="impressions">Initial value of the Impressions property.</param>
        public static Impression CreateImpression(global::System.Int64 id, global::System.String compositeID, global::System.DateTime date, global::System.Int32 companyID, global::System.Int32 marketerID, global::System.Int32 bidID, global::System.Int64 impressions)
        {
            Impression impression = new Impression();
            impression.ID = id;
            impression.CompositeID = compositeID;
            impression.Date = date;
            impression.CompanyID = companyID;
            impression.MarketerID = marketerID;
            impression.BidID = bidID;
            impression.Impressions = impressions;
            return impression;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CompositeID
        {
            get
            {
                return _CompositeID;
            }
            set
            {
                OnCompositeIDChanging(value);
                ReportPropertyChanging("CompositeID");
                _CompositeID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CompositeID");
                OnCompositeIDChanged();
            }
        }
        private global::System.String _CompositeID;
        partial void OnCompositeIDChanging(global::System.String value);
        partial void OnCompositeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CompanyID
        {
            get
            {
                return _CompanyID;
            }
            set
            {
                OnCompanyIDChanging(value);
                ReportPropertyChanging("CompanyID");
                _CompanyID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CompanyID");
                OnCompanyIDChanged();
            }
        }
        private global::System.Int32 _CompanyID;
        partial void OnCompanyIDChanging(global::System.Int32 value);
        partial void OnCompanyIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MarketerID
        {
            get
            {
                return _MarketerID;
            }
            set
            {
                OnMarketerIDChanging(value);
                ReportPropertyChanging("MarketerID");
                _MarketerID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MarketerID");
                OnMarketerIDChanged();
            }
        }
        private global::System.Int32 _MarketerID;
        partial void OnMarketerIDChanging(global::System.Int32 value);
        partial void OnMarketerIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BidID
        {
            get
            {
                return _BidID;
            }
            set
            {
                OnBidIDChanging(value);
                ReportPropertyChanging("BidID");
                _BidID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BidID");
                OnBidIDChanged();
            }
        }
        private global::System.Int32 _BidID;
        partial void OnBidIDChanging(global::System.Int32 value);
        partial void OnBidIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Impressions
        {
            get
            {
                return _Impressions;
            }
            set
            {
                OnImpressionsChanging(value);
                ReportPropertyChanging("Impressions");
                _Impressions = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Impressions");
                OnImpressionsChanged();
            }
        }
        private global::System.Int64 _Impressions;
        partial void OnImpressionsChanging(global::System.Int64 value);
        partial void OnImpressionsChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CIQPlatformModel", Name="MappingCode")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MappingCode : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MappingCode object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="mappedCode">Initial value of the MappedCode property.</param>
        /// <param name="productCode">Initial value of the ProductCode property.</param>
        public static MappingCode CreateMappingCode(global::System.Int32 id, global::System.String mappedCode, global::System.String productCode)
        {
            MappingCode mappingCode = new MappingCode();
            mappingCode.ID = id;
            mappingCode.MappedCode = mappedCode;
            mappingCode.ProductCode = productCode;
            return mappingCode;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MappedCode
        {
            get
            {
                return _MappedCode;
            }
            set
            {
                OnMappedCodeChanging(value);
                ReportPropertyChanging("MappedCode");
                _MappedCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MappedCode");
                OnMappedCodeChanged();
            }
        }
        private global::System.String _MappedCode;
        partial void OnMappedCodeChanging(global::System.String value);
        partial void OnMappedCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProductCode
        {
            get
            {
                return _ProductCode;
            }
            set
            {
                OnProductCodeChanging(value);
                ReportPropertyChanging("ProductCode");
                _ProductCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ProductCode");
                OnProductCodeChanged();
            }
        }
        private global::System.String _ProductCode;
        partial void OnProductCodeChanging(global::System.String value);
        partial void OnProductCodeChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CIQPlatformModel", Name="Member")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Member : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Member object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="first">Initial value of the First property.</param>
        /// <param name="last">Initial value of the Last property.</param>
        /// <param name="eMail">Initial value of the EMail property.</param>
        /// <param name="userID">Initial value of the UserID property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        /// <param name="coID">Initial value of the CoID property.</param>
        public static Member CreateMember(global::System.Int32 id, global::System.String first, global::System.String last, global::System.String eMail, global::System.String userID, global::System.String password, global::System.Int32 coID)
        {
            Member member = new Member();
            member.ID = id;
            member.First = first;
            member.Last = last;
            member.EMail = eMail;
            member.UserID = userID;
            member.Password = password;
            member.CoID = coID;
            return member;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String First
        {
            get
            {
                return _First;
            }
            set
            {
                OnFirstChanging(value);
                ReportPropertyChanging("First");
                _First = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("First");
                OnFirstChanged();
            }
        }
        private global::System.String _First;
        partial void OnFirstChanging(global::System.String value);
        partial void OnFirstChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Last
        {
            get
            {
                return _Last;
            }
            set
            {
                OnLastChanging(value);
                ReportPropertyChanging("Last");
                _Last = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Last");
                OnLastChanged();
            }
        }
        private global::System.String _Last;
        partial void OnLastChanging(global::System.String value);
        partial void OnLastChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EMail
        {
            get
            {
                return _EMail;
            }
            set
            {
                OnEMailChanging(value);
                ReportPropertyChanging("EMail");
                _EMail = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EMail");
                OnEMailChanged();
            }
        }
        private global::System.String _EMail;
        partial void OnEMailChanging(global::System.String value);
        partial void OnEMailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                OnUserIDChanging(value);
                ReportPropertyChanging("UserID");
                _UserID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserID");
                OnUserIDChanged();
            }
        }
        private global::System.String _UserID;
        partial void OnUserIDChanging(global::System.String value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CoID
        {
            get
            {
                return _CoID;
            }
            set
            {
                OnCoIDChanging(value);
                ReportPropertyChanging("CoID");
                _CoID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CoID");
                OnCoIDChanged();
            }
        }
        private global::System.Int32 _CoID;
        partial void OnCoIDChanging(global::System.Int32 value);
        partial void OnCoIDChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CIQPlatformModel", Name="ProductClass")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ProductClass : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ProductClass object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="category">Initial value of the Category property.</param>
        /// <param name="subcategory">Initial value of the Subcategory property.</param>
        /// <param name="productClass1">Initial value of the ProductClass1 property.</param>
        public static ProductClass CreateProductClass(global::System.Int32 id, global::System.String category, global::System.String subcategory, global::System.String productClass1)
        {
            ProductClass productClass = new ProductClass();
            productClass.ID = id;
            productClass.Category = category;
            productClass.Subcategory = subcategory;
            productClass.ProductClass1 = productClass1;
            return productClass;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Category
        {
            get
            {
                return _Category;
            }
            set
            {
                OnCategoryChanging(value);
                ReportPropertyChanging("Category");
                _Category = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Category");
                OnCategoryChanged();
            }
        }
        private global::System.String _Category;
        partial void OnCategoryChanging(global::System.String value);
        partial void OnCategoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Subcategory
        {
            get
            {
                return _Subcategory;
            }
            set
            {
                OnSubcategoryChanging(value);
                ReportPropertyChanging("Subcategory");
                _Subcategory = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Subcategory");
                OnSubcategoryChanged();
            }
        }
        private global::System.String _Subcategory;
        partial void OnSubcategoryChanging(global::System.String value);
        partial void OnSubcategoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProductClass1
        {
            get
            {
                return _ProductClass1;
            }
            set
            {
                OnProductClass1Changing(value);
                ReportPropertyChanging("ProductClass1");
                _ProductClass1 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ProductClass1");
                OnProductClass1Changed();
            }
        }
        private global::System.String _ProductClass1;
        partial void OnProductClass1Changing(global::System.String value);
        partial void OnProductClass1Changed();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CIQPlatformModel", Name="ProductCode")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ProductCode : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ProductCode object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="productCode1">Initial value of the ProductCode1 property.</param>
        /// <param name="prodBlob">Initial value of the ProdBlob property.</param>
        /// <param name="prodClass">Initial value of the ProdClass property.</param>
        public static ProductCode CreateProductCode(global::System.Int32 id, global::System.String productCode1, global::System.String prodBlob, global::System.String prodClass)
        {
            ProductCode productCode = new ProductCode();
            productCode.ID = id;
            productCode.ProductCode1 = productCode1;
            productCode.ProdBlob = prodBlob;
            productCode.ProdClass = prodClass;
            return productCode;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProductCode1
        {
            get
            {
                return _ProductCode1;
            }
            set
            {
                OnProductCode1Changing(value);
                ReportPropertyChanging("ProductCode1");
                _ProductCode1 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ProductCode1");
                OnProductCode1Changed();
            }
        }
        private global::System.String _ProductCode1;
        partial void OnProductCode1Changing(global::System.String value);
        partial void OnProductCode1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProdBlob
        {
            get
            {
                return _ProdBlob;
            }
            set
            {
                OnProdBlobChanging(value);
                ReportPropertyChanging("ProdBlob");
                _ProdBlob = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ProdBlob");
                OnProdBlobChanged();
            }
        }
        private global::System.String _ProdBlob;
        partial void OnProdBlobChanging(global::System.String value);
        partial void OnProdBlobChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProdClass
        {
            get
            {
                return _ProdClass;
            }
            set
            {
                OnProdClassChanging(value);
                ReportPropertyChanging("ProdClass");
                _ProdClass = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ProdClass");
                OnProdClassChanged();
            }
        }
        private global::System.String _ProdClass;
        partial void OnProdClassChanging(global::System.String value);
        partial void OnProdClassChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProdCategory
        {
            get
            {
                return _ProdCategory;
            }
            set
            {
                OnProdCategoryChanging(value);
                ReportPropertyChanging("ProdCategory");
                _ProdCategory = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProdCategory");
                OnProdCategoryChanged();
            }
        }
        private global::System.String _ProdCategory;
        partial void OnProdCategoryChanging(global::System.String value);
        partial void OnProdCategoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProdSubcategory
        {
            get
            {
                return _ProdSubcategory;
            }
            set
            {
                OnProdSubcategoryChanging(value);
                ReportPropertyChanging("ProdSubcategory");
                _ProdSubcategory = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProdSubcategory");
                OnProdSubcategoryChanged();
            }
        }
        private global::System.String _ProdSubcategory;
        partial void OnProdSubcategoryChanging(global::System.String value);
        partial void OnProdSubcategoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CIQPlatformModel", Name="ProductTaxonomy")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ProductTaxonomy : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ProductTaxonomy object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="productClass">Initial value of the ProductClass property.</param>
        /// <param name="property">Initial value of the Property property.</param>
        public static ProductTaxonomy CreateProductTaxonomy(global::System.Int32 id, global::System.String productClass, global::System.String property)
        {
            ProductTaxonomy productTaxonomy = new ProductTaxonomy();
            productTaxonomy.ID = id;
            productTaxonomy.ProductClass = productClass;
            productTaxonomy.Property = property;
            return productTaxonomy;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ProductClass
        {
            get
            {
                return _ProductClass;
            }
            set
            {
                OnProductClassChanging(value);
                ReportPropertyChanging("ProductClass");
                _ProductClass = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ProductClass");
                OnProductClassChanged();
            }
        }
        private global::System.String _ProductClass;
        partial void OnProductClassChanging(global::System.String value);
        partial void OnProductClassChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Property
        {
            get
            {
                return _Property;
            }
            set
            {
                OnPropertyChanging(value);
                ReportPropertyChanging("Property");
                _Property = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Property");
                OnPropertyChanged();
            }
        }
        private global::System.String _Property;
        partial void OnPropertyChanging(global::System.String value);
        partial void OnPropertyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ValidValues
        {
            get
            {
                return _ValidValues;
            }
            set
            {
                OnValidValuesChanging(value);
                ReportPropertyChanging("ValidValues");
                _ValidValues = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ValidValues");
                OnValidValuesChanged();
            }
        }
        private global::System.String _ValidValues;
        partial void OnValidValuesChanging(global::System.String value);
        partial void OnValidValuesChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CIQPlatformModel", Name="ScanActivity")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ScanActivity : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ScanActivity object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="dateTime">Initial value of the DateTime property.</param>
        /// <param name="scanData">Initial value of the ScanData property.</param>
        /// <param name="longitude">Initial value of the Longitude property.</param>
        /// <param name="latitude">Initial value of the Latitude property.</param>
        public static ScanActivity CreateScanActivity(global::System.Int32 id, global::System.DateTime dateTime, global::System.String scanData, global::System.Double longitude, global::System.Double latitude)
        {
            ScanActivity scanActivity = new ScanActivity();
            scanActivity.ID = id;
            scanActivity.DateTime = dateTime;
            scanActivity.ScanData = scanData;
            scanActivity.Longitude = longitude;
            scanActivity.Latitude = latitude;
            return scanActivity;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateTime
        {
            get
            {
                return _DateTime;
            }
            set
            {
                OnDateTimeChanging(value);
                ReportPropertyChanging("DateTime");
                _DateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateTime");
                OnDateTimeChanged();
            }
        }
        private global::System.DateTime _DateTime;
        partial void OnDateTimeChanging(global::System.DateTime value);
        partial void OnDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ScanData
        {
            get
            {
                return _ScanData;
            }
            set
            {
                OnScanDataChanging(value);
                ReportPropertyChanging("ScanData");
                _ScanData = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ScanData");
                OnScanDataChanged();
            }
        }
        private global::System.String _ScanData;
        partial void OnScanDataChanging(global::System.String value);
        partial void OnScanDataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Longitude
        {
            get
            {
                return _Longitude;
            }
            set
            {
                OnLongitudeChanging(value);
                ReportPropertyChanging("Longitude");
                _Longitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Longitude");
                OnLongitudeChanged();
            }
        }
        private global::System.Double _Longitude;
        partial void OnLongitudeChanging(global::System.Double value);
        partial void OnLongitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Latitude
        {
            get
            {
                return _Latitude;
            }
            set
            {
                OnLatitudeChanging(value);
                ReportPropertyChanging("Latitude");
                _Latitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Latitude");
                OnLatitudeChanged();
            }
        }
        private global::System.Double _Latitude;
        partial void OnLatitudeChanging(global::System.Double value);
        partial void OnLatitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Category
        {
            get
            {
                return _Category;
            }
            set
            {
                OnCategoryChanging(value);
                ReportPropertyChanging("Category");
                _Category = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Category");
                OnCategoryChanged();
            }
        }
        private global::System.String _Category;
        partial void OnCategoryChanging(global::System.String value);
        partial void OnCategoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Subcategory
        {
            get
            {
                return _Subcategory;
            }
            set
            {
                OnSubcategoryChanging(value);
                ReportPropertyChanging("Subcategory");
                _Subcategory = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Subcategory");
                OnSubcategoryChanged();
            }
        }
        private global::System.String _Subcategory;
        partial void OnSubcategoryChanging(global::System.String value);
        partial void OnSubcategoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Classification
        {
            get
            {
                return _Classification;
            }
            set
            {
                OnClassificationChanging(value);
                ReportPropertyChanging("Classification");
                _Classification = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Classification");
                OnClassificationChanged();
            }
        }
        private global::System.String _Classification;
        partial void OnClassificationChanging(global::System.String value);
        partial void OnClassificationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProductBlob
        {
            get
            {
                return _ProductBlob;
            }
            set
            {
                OnProductBlobChanging(value);
                ReportPropertyChanging("ProductBlob");
                _ProductBlob = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProductBlob");
                OnProductBlobChanged();
            }
        }
        private global::System.String _ProductBlob;
        partial void OnProductBlobChanging(global::System.String value);
        partial void OnProductBlobChanged();

        #endregion
    
    }

    #endregion
    
}
