//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace WP7AdFinder.CIQAffiliateServices {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ProductAds", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceWebRole", ItemName="CProductAd")]
    public class ProductAds : System.Collections.ObjectModel.ObservableCollection<WP7AdFinder.CIQAffiliateServices.CProductAd> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CProductAd", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceWebRole")]
    public partial class CProductAd : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid AdGuidField;
        
        private string AdTextField;
        
        private string AdTitleField;
        
        private string BrandImageUrlField;
        
        private double DiscountAmountField;
        
        private string ImageUrlField;
        
        private bool IsPercentageField;
        
        private string ManufacturerCodeField;
        
        private int MarketerIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid AdGuid {
            get {
                return this.AdGuidField;
            }
            set {
                if ((this.AdGuidField.Equals(value) != true)) {
                    this.AdGuidField = value;
                    this.RaisePropertyChanged("AdGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdText {
            get {
                return this.AdTextField;
            }
            set {
                if ((object.ReferenceEquals(this.AdTextField, value) != true)) {
                    this.AdTextField = value;
                    this.RaisePropertyChanged("AdText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdTitle {
            get {
                return this.AdTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.AdTitleField, value) != true)) {
                    this.AdTitleField = value;
                    this.RaisePropertyChanged("AdTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BrandImageUrl {
            get {
                return this.BrandImageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.BrandImageUrlField, value) != true)) {
                    this.BrandImageUrlField = value;
                    this.RaisePropertyChanged("BrandImageUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double DiscountAmount {
            get {
                return this.DiscountAmountField;
            }
            set {
                if ((this.DiscountAmountField.Equals(value) != true)) {
                    this.DiscountAmountField = value;
                    this.RaisePropertyChanged("DiscountAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageUrl {
            get {
                return this.ImageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageUrlField, value) != true)) {
                    this.ImageUrlField = value;
                    this.RaisePropertyChanged("ImageUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPercentage {
            get {
                return this.IsPercentageField;
            }
            set {
                if ((this.IsPercentageField.Equals(value) != true)) {
                    this.IsPercentageField = value;
                    this.RaisePropertyChanged("IsPercentage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ManufacturerCode {
            get {
                return this.ManufacturerCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ManufacturerCodeField, value) != true)) {
                    this.ManufacturerCodeField = value;
                    this.RaisePropertyChanged("ManufacturerCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MarketerID {
            get {
                return this.MarketerIDField;
            }
            set {
                if ((this.MarketerIDField.Equals(value) != true)) {
                    this.MarketerIDField = value;
                    this.RaisePropertyChanged("MarketerID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ProductProperties", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceWebRole", ItemName="entry", KeyName="property", ValueName="value")]
    public class ProductProperties : System.Collections.Generic.Dictionary<string, string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CIQAffiliateServices.ICIQPlatform")]
    public interface ICIQPlatform {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ICIQPlatform/GetAdList", ReplyAction="http://tempuri.org/ICIQPlatform/GetAdListResponse")]
        System.IAsyncResult BeginGetAdList(System.Guid affiliateID, string scannedCode, double lon, double lat, int adsToReturn, System.AsyncCallback callback, object asyncState);
        
        WP7AdFinder.CIQAffiliateServices.ProductAds EndGetAdList(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ICIQPlatform/GetAdDetails", ReplyAction="http://tempuri.org/ICIQPlatform/GetAdDetailsResponse")]
        System.IAsyncResult BeginGetAdDetails(System.Guid affiliateID, string scannedCode, double lon, double lat, System.Guid adGuid, System.AsyncCallback callback, object asyncState);
        
        WP7AdFinder.CIQAffiliateServices.CProductAd EndGetAdDetails(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ICIQPlatform/GetAdCoupon", ReplyAction="http://tempuri.org/ICIQPlatform/GetAdCouponResponse")]
        System.IAsyncResult BeginGetAdCoupon(System.Guid affiliateID, string scannedCode, double lon, double lat, System.Guid redeemGuid, System.AsyncCallback callback, object asyncState);
        
        WP7AdFinder.CIQAffiliateServices.CProductAd EndGetAdCoupon(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ICIQPlatform/GetProductInformation", ReplyAction="http://tempuri.org/ICIQPlatform/GetProductInformationResponse")]
        System.IAsyncResult BeginGetProductInformation(System.Guid affiliateID, string scannedCode, double lon, double lat, System.AsyncCallback callback, object asyncState);
        
        WP7AdFinder.CIQAffiliateServices.ProductProperties EndGetProductInformation(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICIQPlatformChannel : WP7AdFinder.CIQAffiliateServices.ICIQPlatform, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAdListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAdListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WP7AdFinder.CIQAffiliateServices.ProductAds Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WP7AdFinder.CIQAffiliateServices.ProductAds)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAdDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAdDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WP7AdFinder.CIQAffiliateServices.CProductAd Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WP7AdFinder.CIQAffiliateServices.CProductAd)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAdCouponCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAdCouponCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WP7AdFinder.CIQAffiliateServices.CProductAd Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WP7AdFinder.CIQAffiliateServices.CProductAd)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetProductInformationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetProductInformationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WP7AdFinder.CIQAffiliateServices.ProductProperties Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WP7AdFinder.CIQAffiliateServices.ProductProperties)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CIQPlatformClient : System.ServiceModel.ClientBase<WP7AdFinder.CIQAffiliateServices.ICIQPlatform>, WP7AdFinder.CIQAffiliateServices.ICIQPlatform {
        
        private BeginOperationDelegate onBeginGetAdListDelegate;
        
        private EndOperationDelegate onEndGetAdListDelegate;
        
        private System.Threading.SendOrPostCallback onGetAdListCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetAdDetailsDelegate;
        
        private EndOperationDelegate onEndGetAdDetailsDelegate;
        
        private System.Threading.SendOrPostCallback onGetAdDetailsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetAdCouponDelegate;
        
        private EndOperationDelegate onEndGetAdCouponDelegate;
        
        private System.Threading.SendOrPostCallback onGetAdCouponCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetProductInformationDelegate;
        
        private EndOperationDelegate onEndGetProductInformationDelegate;
        
        private System.Threading.SendOrPostCallback onGetProductInformationCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public CIQPlatformClient() {
        }
        
        public CIQPlatformClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CIQPlatformClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CIQPlatformClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CIQPlatformClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetAdListCompletedEventArgs> GetAdListCompleted;
        
        public event System.EventHandler<GetAdDetailsCompletedEventArgs> GetAdDetailsCompleted;
        
        public event System.EventHandler<GetAdCouponCompletedEventArgs> GetAdCouponCompleted;
        
        public event System.EventHandler<GetProductInformationCompletedEventArgs> GetProductInformationCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WP7AdFinder.CIQAffiliateServices.ICIQPlatform.BeginGetAdList(System.Guid affiliateID, string scannedCode, double lon, double lat, int adsToReturn, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAdList(affiliateID, scannedCode, lon, lat, adsToReturn, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WP7AdFinder.CIQAffiliateServices.ProductAds WP7AdFinder.CIQAffiliateServices.ICIQPlatform.EndGetAdList(System.IAsyncResult result) {
            return base.Channel.EndGetAdList(result);
        }
        
        private System.IAsyncResult OnBeginGetAdList(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.Guid affiliateID = ((System.Guid)(inValues[0]));
            string scannedCode = ((string)(inValues[1]));
            double lon = ((double)(inValues[2]));
            double lat = ((double)(inValues[3]));
            int adsToReturn = ((int)(inValues[4]));
            return ((WP7AdFinder.CIQAffiliateServices.ICIQPlatform)(this)).BeginGetAdList(affiliateID, scannedCode, lon, lat, adsToReturn, callback, asyncState);
        }
        
        private object[] OnEndGetAdList(System.IAsyncResult result) {
            WP7AdFinder.CIQAffiliateServices.ProductAds retVal = ((WP7AdFinder.CIQAffiliateServices.ICIQPlatform)(this)).EndGetAdList(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAdListCompleted(object state) {
            if ((this.GetAdListCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAdListCompleted(this, new GetAdListCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAdListAsync(System.Guid affiliateID, string scannedCode, double lon, double lat, int adsToReturn) {
            this.GetAdListAsync(affiliateID, scannedCode, lon, lat, adsToReturn, null);
        }
        
        public void GetAdListAsync(System.Guid affiliateID, string scannedCode, double lon, double lat, int adsToReturn, object userState) {
            if ((this.onBeginGetAdListDelegate == null)) {
                this.onBeginGetAdListDelegate = new BeginOperationDelegate(this.OnBeginGetAdList);
            }
            if ((this.onEndGetAdListDelegate == null)) {
                this.onEndGetAdListDelegate = new EndOperationDelegate(this.OnEndGetAdList);
            }
            if ((this.onGetAdListCompletedDelegate == null)) {
                this.onGetAdListCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAdListCompleted);
            }
            base.InvokeAsync(this.onBeginGetAdListDelegate, new object[] {
                        affiliateID,
                        scannedCode,
                        lon,
                        lat,
                        adsToReturn}, this.onEndGetAdListDelegate, this.onGetAdListCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WP7AdFinder.CIQAffiliateServices.ICIQPlatform.BeginGetAdDetails(System.Guid affiliateID, string scannedCode, double lon, double lat, System.Guid adGuid, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAdDetails(affiliateID, scannedCode, lon, lat, adGuid, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WP7AdFinder.CIQAffiliateServices.CProductAd WP7AdFinder.CIQAffiliateServices.ICIQPlatform.EndGetAdDetails(System.IAsyncResult result) {
            return base.Channel.EndGetAdDetails(result);
        }
        
        private System.IAsyncResult OnBeginGetAdDetails(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.Guid affiliateID = ((System.Guid)(inValues[0]));
            string scannedCode = ((string)(inValues[1]));
            double lon = ((double)(inValues[2]));
            double lat = ((double)(inValues[3]));
            System.Guid adGuid = ((System.Guid)(inValues[4]));
            return ((WP7AdFinder.CIQAffiliateServices.ICIQPlatform)(this)).BeginGetAdDetails(affiliateID, scannedCode, lon, lat, adGuid, callback, asyncState);
        }
        
        private object[] OnEndGetAdDetails(System.IAsyncResult result) {
            WP7AdFinder.CIQAffiliateServices.CProductAd retVal = ((WP7AdFinder.CIQAffiliateServices.ICIQPlatform)(this)).EndGetAdDetails(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAdDetailsCompleted(object state) {
            if ((this.GetAdDetailsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAdDetailsCompleted(this, new GetAdDetailsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAdDetailsAsync(System.Guid affiliateID, string scannedCode, double lon, double lat, System.Guid adGuid) {
            this.GetAdDetailsAsync(affiliateID, scannedCode, lon, lat, adGuid, null);
        }
        
        public void GetAdDetailsAsync(System.Guid affiliateID, string scannedCode, double lon, double lat, System.Guid adGuid, object userState) {
            if ((this.onBeginGetAdDetailsDelegate == null)) {
                this.onBeginGetAdDetailsDelegate = new BeginOperationDelegate(this.OnBeginGetAdDetails);
            }
            if ((this.onEndGetAdDetailsDelegate == null)) {
                this.onEndGetAdDetailsDelegate = new EndOperationDelegate(this.OnEndGetAdDetails);
            }
            if ((this.onGetAdDetailsCompletedDelegate == null)) {
                this.onGetAdDetailsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAdDetailsCompleted);
            }
            base.InvokeAsync(this.onBeginGetAdDetailsDelegate, new object[] {
                        affiliateID,
                        scannedCode,
                        lon,
                        lat,
                        adGuid}, this.onEndGetAdDetailsDelegate, this.onGetAdDetailsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WP7AdFinder.CIQAffiliateServices.ICIQPlatform.BeginGetAdCoupon(System.Guid affiliateID, string scannedCode, double lon, double lat, System.Guid redeemGuid, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAdCoupon(affiliateID, scannedCode, lon, lat, redeemGuid, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WP7AdFinder.CIQAffiliateServices.CProductAd WP7AdFinder.CIQAffiliateServices.ICIQPlatform.EndGetAdCoupon(System.IAsyncResult result) {
            return base.Channel.EndGetAdCoupon(result);
        }
        
        private System.IAsyncResult OnBeginGetAdCoupon(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.Guid affiliateID = ((System.Guid)(inValues[0]));
            string scannedCode = ((string)(inValues[1]));
            double lon = ((double)(inValues[2]));
            double lat = ((double)(inValues[3]));
            System.Guid redeemGuid = ((System.Guid)(inValues[4]));
            return ((WP7AdFinder.CIQAffiliateServices.ICIQPlatform)(this)).BeginGetAdCoupon(affiliateID, scannedCode, lon, lat, redeemGuid, callback, asyncState);
        }
        
        private object[] OnEndGetAdCoupon(System.IAsyncResult result) {
            WP7AdFinder.CIQAffiliateServices.CProductAd retVal = ((WP7AdFinder.CIQAffiliateServices.ICIQPlatform)(this)).EndGetAdCoupon(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAdCouponCompleted(object state) {
            if ((this.GetAdCouponCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAdCouponCompleted(this, new GetAdCouponCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAdCouponAsync(System.Guid affiliateID, string scannedCode, double lon, double lat, System.Guid redeemGuid) {
            this.GetAdCouponAsync(affiliateID, scannedCode, lon, lat, redeemGuid, null);
        }
        
        public void GetAdCouponAsync(System.Guid affiliateID, string scannedCode, double lon, double lat, System.Guid redeemGuid, object userState) {
            if ((this.onBeginGetAdCouponDelegate == null)) {
                this.onBeginGetAdCouponDelegate = new BeginOperationDelegate(this.OnBeginGetAdCoupon);
            }
            if ((this.onEndGetAdCouponDelegate == null)) {
                this.onEndGetAdCouponDelegate = new EndOperationDelegate(this.OnEndGetAdCoupon);
            }
            if ((this.onGetAdCouponCompletedDelegate == null)) {
                this.onGetAdCouponCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAdCouponCompleted);
            }
            base.InvokeAsync(this.onBeginGetAdCouponDelegate, new object[] {
                        affiliateID,
                        scannedCode,
                        lon,
                        lat,
                        redeemGuid}, this.onEndGetAdCouponDelegate, this.onGetAdCouponCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WP7AdFinder.CIQAffiliateServices.ICIQPlatform.BeginGetProductInformation(System.Guid affiliateID, string scannedCode, double lon, double lat, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetProductInformation(affiliateID, scannedCode, lon, lat, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WP7AdFinder.CIQAffiliateServices.ProductProperties WP7AdFinder.CIQAffiliateServices.ICIQPlatform.EndGetProductInformation(System.IAsyncResult result) {
            return base.Channel.EndGetProductInformation(result);
        }
        
        private System.IAsyncResult OnBeginGetProductInformation(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.Guid affiliateID = ((System.Guid)(inValues[0]));
            string scannedCode = ((string)(inValues[1]));
            double lon = ((double)(inValues[2]));
            double lat = ((double)(inValues[3]));
            return ((WP7AdFinder.CIQAffiliateServices.ICIQPlatform)(this)).BeginGetProductInformation(affiliateID, scannedCode, lon, lat, callback, asyncState);
        }
        
        private object[] OnEndGetProductInformation(System.IAsyncResult result) {
            WP7AdFinder.CIQAffiliateServices.ProductProperties retVal = ((WP7AdFinder.CIQAffiliateServices.ICIQPlatform)(this)).EndGetProductInformation(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetProductInformationCompleted(object state) {
            if ((this.GetProductInformationCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetProductInformationCompleted(this, new GetProductInformationCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetProductInformationAsync(System.Guid affiliateID, string scannedCode, double lon, double lat) {
            this.GetProductInformationAsync(affiliateID, scannedCode, lon, lat, null);
        }
        
        public void GetProductInformationAsync(System.Guid affiliateID, string scannedCode, double lon, double lat, object userState) {
            if ((this.onBeginGetProductInformationDelegate == null)) {
                this.onBeginGetProductInformationDelegate = new BeginOperationDelegate(this.OnBeginGetProductInformation);
            }
            if ((this.onEndGetProductInformationDelegate == null)) {
                this.onEndGetProductInformationDelegate = new EndOperationDelegate(this.OnEndGetProductInformation);
            }
            if ((this.onGetProductInformationCompletedDelegate == null)) {
                this.onGetProductInformationCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetProductInformationCompleted);
            }
            base.InvokeAsync(this.onBeginGetProductInformationDelegate, new object[] {
                        affiliateID,
                        scannedCode,
                        lon,
                        lat}, this.onEndGetProductInformationDelegate, this.onGetProductInformationCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override WP7AdFinder.CIQAffiliateServices.ICIQPlatform CreateChannel() {
            return new CIQPlatformClientChannel(this);
        }
        
        private class CIQPlatformClientChannel : ChannelBase<WP7AdFinder.CIQAffiliateServices.ICIQPlatform>, WP7AdFinder.CIQAffiliateServices.ICIQPlatform {
            
            public CIQPlatformClientChannel(System.ServiceModel.ClientBase<WP7AdFinder.CIQAffiliateServices.ICIQPlatform> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetAdList(System.Guid affiliateID, string scannedCode, double lon, double lat, int adsToReturn, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[5];
                _args[0] = affiliateID;
                _args[1] = scannedCode;
                _args[2] = lon;
                _args[3] = lat;
                _args[4] = adsToReturn;
                System.IAsyncResult _result = base.BeginInvoke("GetAdList", _args, callback, asyncState);
                return _result;
            }
            
            public WP7AdFinder.CIQAffiliateServices.ProductAds EndGetAdList(System.IAsyncResult result) {
                object[] _args = new object[0];
                WP7AdFinder.CIQAffiliateServices.ProductAds _result = ((WP7AdFinder.CIQAffiliateServices.ProductAds)(base.EndInvoke("GetAdList", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetAdDetails(System.Guid affiliateID, string scannedCode, double lon, double lat, System.Guid adGuid, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[5];
                _args[0] = affiliateID;
                _args[1] = scannedCode;
                _args[2] = lon;
                _args[3] = lat;
                _args[4] = adGuid;
                System.IAsyncResult _result = base.BeginInvoke("GetAdDetails", _args, callback, asyncState);
                return _result;
            }
            
            public WP7AdFinder.CIQAffiliateServices.CProductAd EndGetAdDetails(System.IAsyncResult result) {
                object[] _args = new object[0];
                WP7AdFinder.CIQAffiliateServices.CProductAd _result = ((WP7AdFinder.CIQAffiliateServices.CProductAd)(base.EndInvoke("GetAdDetails", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetAdCoupon(System.Guid affiliateID, string scannedCode, double lon, double lat, System.Guid redeemGuid, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[5];
                _args[0] = affiliateID;
                _args[1] = scannedCode;
                _args[2] = lon;
                _args[3] = lat;
                _args[4] = redeemGuid;
                System.IAsyncResult _result = base.BeginInvoke("GetAdCoupon", _args, callback, asyncState);
                return _result;
            }
            
            public WP7AdFinder.CIQAffiliateServices.CProductAd EndGetAdCoupon(System.IAsyncResult result) {
                object[] _args = new object[0];
                WP7AdFinder.CIQAffiliateServices.CProductAd _result = ((WP7AdFinder.CIQAffiliateServices.CProductAd)(base.EndInvoke("GetAdCoupon", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetProductInformation(System.Guid affiliateID, string scannedCode, double lon, double lat, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[4];
                _args[0] = affiliateID;
                _args[1] = scannedCode;
                _args[2] = lon;
                _args[3] = lat;
                System.IAsyncResult _result = base.BeginInvoke("GetProductInformation", _args, callback, asyncState);
                return _result;
            }
            
            public WP7AdFinder.CIQAffiliateServices.ProductProperties EndGetProductInformation(System.IAsyncResult result) {
                object[] _args = new object[0];
                WP7AdFinder.CIQAffiliateServices.ProductProperties _result = ((WP7AdFinder.CIQAffiliateServices.ProductProperties)(base.EndInvoke("GetProductInformation", _args, result)));
                return _result;
            }
        }
    }
}
