//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace WP7AdFinder.CIQProductIdentityServices {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CProductIdentity", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceWebRole")]
    public partial class CProductIdentity : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string DescriptionField;
        
        private string ProductCategoryField;
        
        private string ProductClassField;
        
        private string ProductIdentityField;
        
        private string ProductSubcategoryField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductCategory {
            get {
                return this.ProductCategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductCategoryField, value) != true)) {
                    this.ProductCategoryField = value;
                    this.RaisePropertyChanged("ProductCategory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductClass {
            get {
                return this.ProductClassField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductClassField, value) != true)) {
                    this.ProductClassField = value;
                    this.RaisePropertyChanged("ProductClass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductIdentity {
            get {
                return this.ProductIdentityField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductIdentityField, value) != true)) {
                    this.ProductIdentityField = value;
                    this.RaisePropertyChanged("ProductIdentity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductSubcategory {
            get {
                return this.ProductSubcategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductSubcategoryField, value) != true)) {
                    this.ProductSubcategoryField = value;
                    this.RaisePropertyChanged("ProductSubcategory");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CIQProductIdentityServices.ICIQProductIdentityServices")]
    public interface ICIQProductIdentityServices {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ICIQProductIdentityServices/CreateProductIdentityInstance", ReplyAction="http://tempuri.org/ICIQProductIdentityServices/CreateProductIdentityInstanceRespo" +
            "nse")]
        System.IAsyncResult BeginCreateProductIdentityInstance(System.AsyncCallback callback, object asyncState);
        
        WP7AdFinder.CIQProductIdentityServices.CProductIdentity EndCreateProductIdentityInstance(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ICIQProductIdentityServices/SaveProductIdentity", ReplyAction="http://tempuri.org/ICIQProductIdentityServices/SaveProductIdentityResponse")]
        System.IAsyncResult BeginSaveProductIdentity(WP7AdFinder.CIQProductIdentityServices.CProductIdentity cPI, string flattenedProduct, System.AsyncCallback callback, object asyncState);
        
        bool EndSaveProductIdentity(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ICIQProductIdentityServices/QueryKind", ReplyAction="http://tempuri.org/ICIQProductIdentityServices/QueryKindResponse")]
        System.IAsyncResult BeginQueryKind(string flattenedProduct, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<WP7AdFinder.CIQProductIdentityServices.CProductIdentity> EndQueryKind(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ICIQProductIdentityServices/MapIdentity", ReplyAction="http://tempuri.org/ICIQProductIdentityServices/MapIdentityResponse")]
        System.IAsyncResult BeginMapIdentity(string mapping, string productIdentity, System.AsyncCallback callback, object asyncState);
        
        bool EndMapIdentity(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ICIQProductIdentityServices/QueryIdentity", ReplyAction="http://tempuri.org/ICIQProductIdentityServices/QueryIdentityResponse")]
        System.IAsyncResult BeginQueryIdentity(string productCode, System.AsyncCallback callback, object asyncState);
        
        WP7AdFinder.CIQProductIdentityServices.CProductIdentity EndQueryIdentity(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ICIQProductIdentityServices/QueryProduct", ReplyAction="http://tempuri.org/ICIQProductIdentityServices/QueryProductResponse")]
        System.IAsyncResult BeginQueryProduct(string productCode, System.AsyncCallback callback, object asyncState);
        
        string EndQueryProduct(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICIQProductIdentityServicesChannel : WP7AdFinder.CIQProductIdentityServices.ICIQProductIdentityServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreateProductIdentityInstanceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CreateProductIdentityInstanceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WP7AdFinder.CIQProductIdentityServices.CProductIdentity Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WP7AdFinder.CIQProductIdentityServices.CProductIdentity)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SaveProductIdentityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SaveProductIdentityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QueryKindCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public QueryKindCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<WP7AdFinder.CIQProductIdentityServices.CProductIdentity> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<WP7AdFinder.CIQProductIdentityServices.CProductIdentity>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MapIdentityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public MapIdentityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QueryIdentityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public QueryIdentityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public WP7AdFinder.CIQProductIdentityServices.CProductIdentity Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((WP7AdFinder.CIQProductIdentityServices.CProductIdentity)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QueryProductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public QueryProductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CIQProductIdentityServicesClient : System.ServiceModel.ClientBase<WP7AdFinder.CIQProductIdentityServices.ICIQProductIdentityServices>, WP7AdFinder.CIQProductIdentityServices.ICIQProductIdentityServices {
        
        private BeginOperationDelegate onBeginCreateProductIdentityInstanceDelegate;
        
        private EndOperationDelegate onEndCreateProductIdentityInstanceDelegate;
        
        private System.Threading.SendOrPostCallback onCreateProductIdentityInstanceCompletedDelegate;
        
        private BeginOperationDelegate onBeginSaveProductIdentityDelegate;
        
        private EndOperationDelegate onEndSaveProductIdentityDelegate;
        
        private System.Threading.SendOrPostCallback onSaveProductIdentityCompletedDelegate;
        
        private BeginOperationDelegate onBeginQueryKindDelegate;
        
        private EndOperationDelegate onEndQueryKindDelegate;
        
        private System.Threading.SendOrPostCallback onQueryKindCompletedDelegate;
        
        private BeginOperationDelegate onBeginMapIdentityDelegate;
        
        private EndOperationDelegate onEndMapIdentityDelegate;
        
        private System.Threading.SendOrPostCallback onMapIdentityCompletedDelegate;
        
        private BeginOperationDelegate onBeginQueryIdentityDelegate;
        
        private EndOperationDelegate onEndQueryIdentityDelegate;
        
        private System.Threading.SendOrPostCallback onQueryIdentityCompletedDelegate;
        
        private BeginOperationDelegate onBeginQueryProductDelegate;
        
        private EndOperationDelegate onEndQueryProductDelegate;
        
        private System.Threading.SendOrPostCallback onQueryProductCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public CIQProductIdentityServicesClient() {
        }
        
        public CIQProductIdentityServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CIQProductIdentityServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CIQProductIdentityServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CIQProductIdentityServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<CreateProductIdentityInstanceCompletedEventArgs> CreateProductIdentityInstanceCompleted;
        
        public event System.EventHandler<SaveProductIdentityCompletedEventArgs> SaveProductIdentityCompleted;
        
        public event System.EventHandler<QueryKindCompletedEventArgs> QueryKindCompleted;
        
        public event System.EventHandler<MapIdentityCompletedEventArgs> MapIdentityCompleted;
        
        public event System.EventHandler<QueryIdentityCompletedEventArgs> QueryIdentityCompleted;
        
        public event System.EventHandler<QueryProductCompletedEventArgs> QueryProductCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WP7AdFinder.CIQProductIdentityServices.ICIQProductIdentityServices.BeginCreateProductIdentityInstance(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCreateProductIdentityInstance(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WP7AdFinder.CIQProductIdentityServices.CProductIdentity WP7AdFinder.CIQProductIdentityServices.ICIQProductIdentityServices.EndCreateProductIdentityInstance(System.IAsyncResult result) {
            return base.Channel.EndCreateProductIdentityInstance(result);
        }
        
        private System.IAsyncResult OnBeginCreateProductIdentityInstance(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((WP7AdFinder.CIQProductIdentityServices.ICIQProductIdentityServices)(this)).BeginCreateProductIdentityInstance(callback, asyncState);
        }
        
        private object[] OnEndCreateProductIdentityInstance(System.IAsyncResult result) {
            WP7AdFinder.CIQProductIdentityServices.CProductIdentity retVal = ((WP7AdFinder.CIQProductIdentityServices.ICIQProductIdentityServices)(this)).EndCreateProductIdentityInstance(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCreateProductIdentityInstanceCompleted(object state) {
            if ((this.CreateProductIdentityInstanceCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CreateProductIdentityInstanceCompleted(this, new CreateProductIdentityInstanceCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CreateProductIdentityInstanceAsync() {
            this.CreateProductIdentityInstanceAsync(null);
        }
        
        public void CreateProductIdentityInstanceAsync(object userState) {
            if ((this.onBeginCreateProductIdentityInstanceDelegate == null)) {
                this.onBeginCreateProductIdentityInstanceDelegate = new BeginOperationDelegate(this.OnBeginCreateProductIdentityInstance);
            }
            if ((this.onEndCreateProductIdentityInstanceDelegate == null)) {
                this.onEndCreateProductIdentityInstanceDelegate = new EndOperationDelegate(this.OnEndCreateProductIdentityInstance);
            }
            if ((this.onCreateProductIdentityInstanceCompletedDelegate == null)) {
                this.onCreateProductIdentityInstanceCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCreateProductIdentityInstanceCompleted);
            }
            base.InvokeAsync(this.onBeginCreateProductIdentityInstanceDelegate, null, this.onEndCreateProductIdentityInstanceDelegate, this.onCreateProductIdentityInstanceCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WP7AdFinder.CIQProductIdentityServices.ICIQProductIdentityServices.BeginSaveProductIdentity(WP7AdFinder.CIQProductIdentityServices.CProductIdentity cPI, string flattenedProduct, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSaveProductIdentity(cPI, flattenedProduct, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool WP7AdFinder.CIQProductIdentityServices.ICIQProductIdentityServices.EndSaveProductIdentity(System.IAsyncResult result) {
            return base.Channel.EndSaveProductIdentity(result);
        }
        
        private System.IAsyncResult OnBeginSaveProductIdentity(object[] inValues, System.AsyncCallback callback, object asyncState) {
            WP7AdFinder.CIQProductIdentityServices.CProductIdentity cPI = ((WP7AdFinder.CIQProductIdentityServices.CProductIdentity)(inValues[0]));
            string flattenedProduct = ((string)(inValues[1]));
            return ((WP7AdFinder.CIQProductIdentityServices.ICIQProductIdentityServices)(this)).BeginSaveProductIdentity(cPI, flattenedProduct, callback, asyncState);
        }
        
        private object[] OnEndSaveProductIdentity(System.IAsyncResult result) {
            bool retVal = ((WP7AdFinder.CIQProductIdentityServices.ICIQProductIdentityServices)(this)).EndSaveProductIdentity(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSaveProductIdentityCompleted(object state) {
            if ((this.SaveProductIdentityCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SaveProductIdentityCompleted(this, new SaveProductIdentityCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SaveProductIdentityAsync(WP7AdFinder.CIQProductIdentityServices.CProductIdentity cPI, string flattenedProduct) {
            this.SaveProductIdentityAsync(cPI, flattenedProduct, null);
        }
        
        public void SaveProductIdentityAsync(WP7AdFinder.CIQProductIdentityServices.CProductIdentity cPI, string flattenedProduct, object userState) {
            if ((this.onBeginSaveProductIdentityDelegate == null)) {
                this.onBeginSaveProductIdentityDelegate = new BeginOperationDelegate(this.OnBeginSaveProductIdentity);
            }
            if ((this.onEndSaveProductIdentityDelegate == null)) {
                this.onEndSaveProductIdentityDelegate = new EndOperationDelegate(this.OnEndSaveProductIdentity);
            }
            if ((this.onSaveProductIdentityCompletedDelegate == null)) {
                this.onSaveProductIdentityCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSaveProductIdentityCompleted);
            }
            base.InvokeAsync(this.onBeginSaveProductIdentityDelegate, new object[] {
                        cPI,
                        flattenedProduct}, this.onEndSaveProductIdentityDelegate, this.onSaveProductIdentityCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WP7AdFinder.CIQProductIdentityServices.ICIQProductIdentityServices.BeginQueryKind(string flattenedProduct, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginQueryKind(flattenedProduct, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<WP7AdFinder.CIQProductIdentityServices.CProductIdentity> WP7AdFinder.CIQProductIdentityServices.ICIQProductIdentityServices.EndQueryKind(System.IAsyncResult result) {
            return base.Channel.EndQueryKind(result);
        }
        
        private System.IAsyncResult OnBeginQueryKind(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string flattenedProduct = ((string)(inValues[0]));
            return ((WP7AdFinder.CIQProductIdentityServices.ICIQProductIdentityServices)(this)).BeginQueryKind(flattenedProduct, callback, asyncState);
        }
        
        private object[] OnEndQueryKind(System.IAsyncResult result) {
            System.Collections.Generic.List<WP7AdFinder.CIQProductIdentityServices.CProductIdentity> retVal = ((WP7AdFinder.CIQProductIdentityServices.ICIQProductIdentityServices)(this)).EndQueryKind(result);
            return new object[] {
                    retVal};
        }
        
        private void OnQueryKindCompleted(object state) {
            if ((this.QueryKindCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.QueryKindCompleted(this, new QueryKindCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void QueryKindAsync(string flattenedProduct) {
            this.QueryKindAsync(flattenedProduct, null);
        }
        
        public void QueryKindAsync(string flattenedProduct, object userState) {
            if ((this.onBeginQueryKindDelegate == null)) {
                this.onBeginQueryKindDelegate = new BeginOperationDelegate(this.OnBeginQueryKind);
            }
            if ((this.onEndQueryKindDelegate == null)) {
                this.onEndQueryKindDelegate = new EndOperationDelegate(this.OnEndQueryKind);
            }
            if ((this.onQueryKindCompletedDelegate == null)) {
                this.onQueryKindCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnQueryKindCompleted);
            }
            base.InvokeAsync(this.onBeginQueryKindDelegate, new object[] {
                        flattenedProduct}, this.onEndQueryKindDelegate, this.onQueryKindCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WP7AdFinder.CIQProductIdentityServices.ICIQProductIdentityServices.BeginMapIdentity(string mapping, string productIdentity, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginMapIdentity(mapping, productIdentity, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool WP7AdFinder.CIQProductIdentityServices.ICIQProductIdentityServices.EndMapIdentity(System.IAsyncResult result) {
            return base.Channel.EndMapIdentity(result);
        }
        
        private System.IAsyncResult OnBeginMapIdentity(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string mapping = ((string)(inValues[0]));
            string productIdentity = ((string)(inValues[1]));
            return ((WP7AdFinder.CIQProductIdentityServices.ICIQProductIdentityServices)(this)).BeginMapIdentity(mapping, productIdentity, callback, asyncState);
        }
        
        private object[] OnEndMapIdentity(System.IAsyncResult result) {
            bool retVal = ((WP7AdFinder.CIQProductIdentityServices.ICIQProductIdentityServices)(this)).EndMapIdentity(result);
            return new object[] {
                    retVal};
        }
        
        private void OnMapIdentityCompleted(object state) {
            if ((this.MapIdentityCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.MapIdentityCompleted(this, new MapIdentityCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void MapIdentityAsync(string mapping, string productIdentity) {
            this.MapIdentityAsync(mapping, productIdentity, null);
        }
        
        public void MapIdentityAsync(string mapping, string productIdentity, object userState) {
            if ((this.onBeginMapIdentityDelegate == null)) {
                this.onBeginMapIdentityDelegate = new BeginOperationDelegate(this.OnBeginMapIdentity);
            }
            if ((this.onEndMapIdentityDelegate == null)) {
                this.onEndMapIdentityDelegate = new EndOperationDelegate(this.OnEndMapIdentity);
            }
            if ((this.onMapIdentityCompletedDelegate == null)) {
                this.onMapIdentityCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnMapIdentityCompleted);
            }
            base.InvokeAsync(this.onBeginMapIdentityDelegate, new object[] {
                        mapping,
                        productIdentity}, this.onEndMapIdentityDelegate, this.onMapIdentityCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WP7AdFinder.CIQProductIdentityServices.ICIQProductIdentityServices.BeginQueryIdentity(string productCode, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginQueryIdentity(productCode, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WP7AdFinder.CIQProductIdentityServices.CProductIdentity WP7AdFinder.CIQProductIdentityServices.ICIQProductIdentityServices.EndQueryIdentity(System.IAsyncResult result) {
            return base.Channel.EndQueryIdentity(result);
        }
        
        private System.IAsyncResult OnBeginQueryIdentity(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string productCode = ((string)(inValues[0]));
            return ((WP7AdFinder.CIQProductIdentityServices.ICIQProductIdentityServices)(this)).BeginQueryIdentity(productCode, callback, asyncState);
        }
        
        private object[] OnEndQueryIdentity(System.IAsyncResult result) {
            WP7AdFinder.CIQProductIdentityServices.CProductIdentity retVal = ((WP7AdFinder.CIQProductIdentityServices.ICIQProductIdentityServices)(this)).EndQueryIdentity(result);
            return new object[] {
                    retVal};
        }
        
        private void OnQueryIdentityCompleted(object state) {
            if ((this.QueryIdentityCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.QueryIdentityCompleted(this, new QueryIdentityCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void QueryIdentityAsync(string productCode) {
            this.QueryIdentityAsync(productCode, null);
        }
        
        public void QueryIdentityAsync(string productCode, object userState) {
            if ((this.onBeginQueryIdentityDelegate == null)) {
                this.onBeginQueryIdentityDelegate = new BeginOperationDelegate(this.OnBeginQueryIdentity);
            }
            if ((this.onEndQueryIdentityDelegate == null)) {
                this.onEndQueryIdentityDelegate = new EndOperationDelegate(this.OnEndQueryIdentity);
            }
            if ((this.onQueryIdentityCompletedDelegate == null)) {
                this.onQueryIdentityCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnQueryIdentityCompleted);
            }
            base.InvokeAsync(this.onBeginQueryIdentityDelegate, new object[] {
                        productCode}, this.onEndQueryIdentityDelegate, this.onQueryIdentityCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult WP7AdFinder.CIQProductIdentityServices.ICIQProductIdentityServices.BeginQueryProduct(string productCode, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginQueryProduct(productCode, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string WP7AdFinder.CIQProductIdentityServices.ICIQProductIdentityServices.EndQueryProduct(System.IAsyncResult result) {
            return base.Channel.EndQueryProduct(result);
        }
        
        private System.IAsyncResult OnBeginQueryProduct(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string productCode = ((string)(inValues[0]));
            return ((WP7AdFinder.CIQProductIdentityServices.ICIQProductIdentityServices)(this)).BeginQueryProduct(productCode, callback, asyncState);
        }
        
        private object[] OnEndQueryProduct(System.IAsyncResult result) {
            string retVal = ((WP7AdFinder.CIQProductIdentityServices.ICIQProductIdentityServices)(this)).EndQueryProduct(result);
            return new object[] {
                    retVal};
        }
        
        private void OnQueryProductCompleted(object state) {
            if ((this.QueryProductCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.QueryProductCompleted(this, new QueryProductCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void QueryProductAsync(string productCode) {
            this.QueryProductAsync(productCode, null);
        }
        
        public void QueryProductAsync(string productCode, object userState) {
            if ((this.onBeginQueryProductDelegate == null)) {
                this.onBeginQueryProductDelegate = new BeginOperationDelegate(this.OnBeginQueryProduct);
            }
            if ((this.onEndQueryProductDelegate == null)) {
                this.onEndQueryProductDelegate = new EndOperationDelegate(this.OnEndQueryProduct);
            }
            if ((this.onQueryProductCompletedDelegate == null)) {
                this.onQueryProductCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnQueryProductCompleted);
            }
            base.InvokeAsync(this.onBeginQueryProductDelegate, new object[] {
                        productCode}, this.onEndQueryProductDelegate, this.onQueryProductCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override WP7AdFinder.CIQProductIdentityServices.ICIQProductIdentityServices CreateChannel() {
            return new CIQProductIdentityServicesClientChannel(this);
        }
        
        private class CIQProductIdentityServicesClientChannel : ChannelBase<WP7AdFinder.CIQProductIdentityServices.ICIQProductIdentityServices>, WP7AdFinder.CIQProductIdentityServices.ICIQProductIdentityServices {
            
            public CIQProductIdentityServicesClientChannel(System.ServiceModel.ClientBase<WP7AdFinder.CIQProductIdentityServices.ICIQProductIdentityServices> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginCreateProductIdentityInstance(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("CreateProductIdentityInstance", _args, callback, asyncState);
                return _result;
            }
            
            public WP7AdFinder.CIQProductIdentityServices.CProductIdentity EndCreateProductIdentityInstance(System.IAsyncResult result) {
                object[] _args = new object[0];
                WP7AdFinder.CIQProductIdentityServices.CProductIdentity _result = ((WP7AdFinder.CIQProductIdentityServices.CProductIdentity)(base.EndInvoke("CreateProductIdentityInstance", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSaveProductIdentity(WP7AdFinder.CIQProductIdentityServices.CProductIdentity cPI, string flattenedProduct, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = cPI;
                _args[1] = flattenedProduct;
                System.IAsyncResult _result = base.BeginInvoke("SaveProductIdentity", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndSaveProductIdentity(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("SaveProductIdentity", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginQueryKind(string flattenedProduct, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = flattenedProduct;
                System.IAsyncResult _result = base.BeginInvoke("QueryKind", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<WP7AdFinder.CIQProductIdentityServices.CProductIdentity> EndQueryKind(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<WP7AdFinder.CIQProductIdentityServices.CProductIdentity> _result = ((System.Collections.Generic.List<WP7AdFinder.CIQProductIdentityServices.CProductIdentity>)(base.EndInvoke("QueryKind", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginMapIdentity(string mapping, string productIdentity, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = mapping;
                _args[1] = productIdentity;
                System.IAsyncResult _result = base.BeginInvoke("MapIdentity", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndMapIdentity(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("MapIdentity", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginQueryIdentity(string productCode, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = productCode;
                System.IAsyncResult _result = base.BeginInvoke("QueryIdentity", _args, callback, asyncState);
                return _result;
            }
            
            public WP7AdFinder.CIQProductIdentityServices.CProductIdentity EndQueryIdentity(System.IAsyncResult result) {
                object[] _args = new object[0];
                WP7AdFinder.CIQProductIdentityServices.CProductIdentity _result = ((WP7AdFinder.CIQProductIdentityServices.CProductIdentity)(base.EndInvoke("QueryIdentity", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginQueryProduct(string productCode, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = productCode;
                System.IAsyncResult _result = base.BeginInvoke("QueryProduct", _args, callback, asyncState);
                return _result;
            }
            
            public string EndQueryProduct(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("QueryProduct", _args, result)));
                return _result;
            }
        }
    }
}
